{
  "formatVersion": "1.1",
  "component": {
    "url": "../../navigation-common/9999.0.0-SNAPSHOT/navigation-common-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.androidx.navigation",
    "module": "navigation-common",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-linuxX64Main-9999.0.0-SNAPSHOT.klib",
          "url": "navigation-common-linuxx64-9999.0.0-SNAPSHOT.klib",
          "size": 314304,
          "sha512": "9b05aa97daf27454709d3c504b3532c9c36daaaae8fb8ace865744432ed3364fa370f509f3be8ebb1ac6658981b7f36f0c54c7af3720e4e4543a1bc0c35d32d2",
          "sha256": "81a4851c1f34e7b4745ee335c36589b756028334739c5e776acfbc16d35a0b0a",
          "sha1": "34bf793946a8edb3d0ea96cfd5c70a5f5357ed67",
          "md5": "5436840d167c9d2522aec7770e580d7b"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "navigation-common-linuxx64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "navigation-common-linuxx64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 102523,
          "sha512": "47be829986b1e5255e66bc6ee498351e79d9043e8cdedee329327735572a9bef2f5cbf4b46426a4e518754cf958fd11a7e22fa78e7cdff6f4eaf5aa3157623e9",
          "sha256": "b3aadea9f19b2b95ce46e4face25d5ea95ad387b260380ee8714093587c667d6",
          "sha1": "09fd738556344ad49e7b64b261bc2a889d330d1b",
          "md5": "96f8baf6fe8b16139dc68c74fd561a97"
        }
      ]
    }
  ]
}