{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lifecycle-runtime/9999.0.0-SNAPSHOT/lifecycle-runtime-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.androidx.lifecycle",
    "module": "lifecycle-runtime",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-watchosArm32Main-9999.0.0-SNAPSHOT.klib",
          "url": "lifecycle-runtime-watchosarm32-9999.0.0-SNAPSHOT.klib",
          "size": 37511,
          "sha512": "2679749d1fc7ac083835778f92bfc18782692e3e95022d4e2831e80f90e406bb9aee14fa0c74cd1ab7f117b68100eee90840ab5718d043333db0fba63295c9c7",
          "sha256": "23001254dc336b9477adc5ed9f117eeda677d58fd4a895af30151565a8463fad",
          "sha1": "f9028809b62285bbf94410d7abd4d2b0b65bdeb2",
          "md5": "0ca579cc2d0315d8df02895f6dcf5144"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "lifecycle-runtime-watchosarm32-9999.0.0-SNAPSHOT-sources.jar",
          "url": "lifecycle-runtime-watchosarm32-9999.0.0-SNAPSHOT-sources.jar",
          "size": 16213,
          "sha512": "e4881661f2f10785ad8781db9e20ede87c31501c58217ef2e1d8ac1056bff783a8df4a2ccd584d238898d5486ff7fe966823a2c7b3a157828006d04e97dccf6f",
          "sha256": "3876298b506fcebea0d444dbcbfdeda19d9e1bfe65b030969df3fc4cff0361b2",
          "sha1": "1fcdd4bb960d91ee85debe491479b55846a3b037",
          "md5": "f0f108e4feeddd964e5597c0a93049c7"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-watchosarm32-9999.0.0-SNAPSHOT-metadata.jar",
          "url": "lifecycle-runtime-watchosarm32-9999.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}