{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-navigation/9999.0.0-SNAPSHOT/material-navigation-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.material",
    "module": "material-navigation",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "material-navigation-js-9999.0.0-SNAPSHOT.klib",
          "url": "material-navigation-js-9999.0.0-SNAPSHOT.klib",
          "size": 41923,
          "sha512": "ae2bb2f09f6da533780ce9dd2b901c096710bef8e9a104cd0dc81c4a60c5d101deb04ed6c6e9965c8fcaed65d6667e6352b8408ac46f292303dd6de85c83e684",
          "sha256": "8f7981c0a2c821e1bc3e72faade1d96884d74c5342b48f12804ee384d5a2a0aa",
          "sha1": "b77fa6ce5d98729e6d1cc4b476705189f530dd2f",
          "md5": "60bc049472604925c89e176bdb5a7c69"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "material-navigation-js-9999.0.0-SNAPSHOT.klib",
          "url": "material-navigation-js-9999.0.0-SNAPSHOT.klib",
          "size": 41923,
          "sha512": "ae2bb2f09f6da533780ce9dd2b901c096710bef8e9a104cd0dc81c4a60c5d101deb04ed6c6e9965c8fcaed65d6667e6352b8408ac46f292303dd6de85c83e684",
          "sha256": "8f7981c0a2c821e1bc3e72faade1d96884d74c5342b48f12804ee384d5a2a0aa",
          "sha1": "b77fa6ce5d98729e6d1cc4b476705189f530dd2f",
          "md5": "60bc049472604925c89e176bdb5a7c69"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "material-navigation-js-9999.0.0-SNAPSHOT-sources.jar",
          "url": "material-navigation-js-9999.0.0-SNAPSHOT-sources.jar",
          "size": 11570,
          "sha512": "397c1283b60ee70cc0326f711f726846f08495ae5793358a0f6bfe4747cbd78d81025e247e4018912858e4782e10445ed81186f7da6068c83f17fb091023b303",
          "sha256": "d9bea1972c3ec3db40a1bc2e410f1696ce9a42db21675fa9b07a606bae2bf933",
          "sha1": "cc6aec6958b041ee1508926435024ed0626759b6",
          "md5": "d8cef57940affed31e74476e20d72aa6"
        }
      ]
    }
  ]
}