{
  "formatVersion": "1.1",
  "component": {
    "url": "../../savedstate/9999.0.0-SNAPSHOT/savedstate-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.androidx.savedstate",
    "module": "savedstate",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-linuxArm64Main-9999.0.0-SNAPSHOT.klib",
          "url": "savedstate-linuxarm64-9999.0.0-SNAPSHOT.klib",
          "size": 93936,
          "sha512": "a2e352f8bd3d63ae5ced78dbf33963ed0230dcfe5b3329fa2938475d89f326188ec4bb47d8d1573d00eb85498d5aa74e21001cfbbb2e30f8f3519cdcfb18fd34",
          "sha256": "3dc9f2118fa2fdb2727e7a3ec41fb01dc06e2f1078b0b6ec3a43b488129c0142",
          "sha1": "2fe055c3fd728bd35485c1d5a2d2fa281b9ac2df",
          "md5": "ffa88352e62cc0edb7972a43730ada94"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "savedstate-linuxarm64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "savedstate-linuxarm64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 35714,
          "sha512": "44a2551cbb4ef93284cc364578a26702273d42df3236f3a8d2a75bacb5346c056dfc8b582ce4847d3647c9d13c698ebcda18bee268bc29f4d8d4b33d740aef6c",
          "sha256": "8dddd47702546e0c82b5650906f870e8019de0dbe26bc0fd1d561bfa76068747",
          "sha1": "64027e150b4a488dcc3aeed761c708084fd603a8",
          "md5": "36fbd15c378d3ee36cb6f736ff45aea9"
        }
      ]
    }
  ]
}