{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation/9999.0.0-SNAPSHOT/foundation-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.foundation",
    "module": "foundation",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.9.3"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "foundation-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 3427171,
          "sha512": "e7cc2d25414f5bd2ccd5569fe2bde404cb0ce840412129879ba636237d99e74f32b6d76ab10aa0e76f741a0d1acbeb18e5904346b8805e05fb5e1155e501438e",
          "sha256": "45c677165fc6995974a87958a8a32cd18f6a41a1703edc68676ebeb268b4f24f",
          "sha1": "079f6434ed0c2376c7af83c370055052681dc236",
          "md5": "6d69d8013abcaf3c0a81f996193a362c"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.3"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.9.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "foundation-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 3427171,
          "sha512": "e7cc2d25414f5bd2ccd5569fe2bde404cb0ce840412129879ba636237d99e74f32b6d76ab10aa0e76f741a0d1acbeb18e5904346b8805e05fb5e1155e501438e",
          "sha256": "45c677165fc6995974a87958a8a32cd18f6a41a1703edc68676ebeb268b4f24f",
          "sha1": "079f6434ed0c2376c7af83c370055052681dc236",
          "md5": "6d69d8013abcaf3c0a81f996193a362c"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "foundation-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "url": "foundation-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "size": 888979,
          "sha512": "377ac1b3b27fd3b5a5ab6d96c6d89db840448966e6c4e70009e0cdae1b9b543d11b7762ede0f7474583dd40d7bc5ac63b49828cb694a0383210fe3961bff3289",
          "sha256": "71b5081bb30ff1f3df4dee8e975d9f2d8a99d65c3742bca5203a1980a805d1dd",
          "sha1": "e4b10689f2fde64c5368929c529c492a9a9bd6a6",
          "md5": "beb3fa15f06a5209ad7a9d26cbe4603b"
        }
      ]
    }
  ]
}