{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-ripple/9999.0.0-SNAPSHOT/material-ripple-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.material",
    "module": "material-ripple",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-js-9999.0.0-SNAPSHOT.klib",
          "url": "material-ripple-js-9999.0.0-SNAPSHOT.klib",
          "size": 57748,
          "sha512": "bdb301949b82f82abadbf8ee952677fadd19ab3336554ca7588f4ebd826a96fec432e1c20e16dfb6ad3b9a94db46f768fa6872588066d7ef72db22b46673d9ca",
          "sha256": "f96fd097d0ce581146a669e5e5578def2a66935ac547120b1251fcd95d5a8867",
          "sha1": "5f621be31013471c70ded2f5558d0e09186ccac1",
          "md5": "fbc58a30772e912c165c098979a7f591"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-js-9999.0.0-SNAPSHOT.klib",
          "url": "material-ripple-js-9999.0.0-SNAPSHOT.klib",
          "size": 57748,
          "sha512": "bdb301949b82f82abadbf8ee952677fadd19ab3336554ca7588f4ebd826a96fec432e1c20e16dfb6ad3b9a94db46f768fa6872588066d7ef72db22b46673d9ca",
          "sha256": "f96fd097d0ce581146a669e5e5578def2a66935ac547120b1251fcd95d5a8867",
          "sha1": "5f621be31013471c70ded2f5558d0e09186ccac1",
          "md5": "fbc58a30772e912c165c098979a7f591"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "material-ripple-js-9999.0.0-SNAPSHOT-sources.jar",
          "url": "material-ripple-js-9999.0.0-SNAPSHOT-sources.jar",
          "size": 15155,
          "sha512": "25bfb0749142341f01286e8d73b3c7f13484c99a4371f71c1dbbc1255d93965c9f0ce79dba7a9d2b2ec3df3ee74282e5017da2dde5e8528caa5c393d1622faa2",
          "sha256": "0a7c4f2293831fcfe52f3f294000cb338f9d8ec18499ca3e6adf3c5f3d391180",
          "sha1": "72e0376dbad6b3fbb014c5368599840f23399c05",
          "md5": "5af7b1c99bd53c2c30d0ed1aca8d872f"
        }
      ]
    }
  ]
}