{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/9999.0.0-SNAPSHOT/runtime-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.runtime",
    "module": "runtime",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "runtime-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 1685712,
          "sha512": "e196b1600bcf3d28a68cdec1d4b2c32f8981f9797351636ef03f9158c00966bcb0a057057f9c948eeea075d72c167ef334cd80204270e893edec80bcdc58a09e",
          "sha256": "4973fbc33df3798d6a1853f56525b84e028090a2fa239c30e4525c23f9e3a900",
          "sha1": "1664d3961a5e857240176694afafda74d053339e",
          "md5": "524465cc4c28d8452eae154fe01b8e16"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "runtime-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 1685712,
          "sha512": "e196b1600bcf3d28a68cdec1d4b2c32f8981f9797351636ef03f9158c00966bcb0a057057f9c948eeea075d72c167ef334cd80204270e893edec80bcdc58a09e",
          "sha256": "4973fbc33df3798d6a1853f56525b84e028090a2fa239c30e4525c23f9e3a900",
          "sha1": "1664d3961a5e857240176694afafda74d053339e",
          "md5": "524465cc4c28d8452eae154fe01b8e16"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "runtime-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "url": "runtime-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "size": 416255,
          "sha512": "eb7ca62847749e355d46bd7aca3f8658afc702607ad5528ad1efdce7251f7cce99faa389d295f3ca84d751c6b11fbb3b1fcdb1b3277c4a1fce84a120cee287f0",
          "sha256": "eb222ae6c1e11c78730d266a9c6f8cdb80616b96cb982442c229d6f987131b7b",
          "sha1": "c1f9bbb1a258b4e6c32fa944dcc048d6ddfc5639",
          "md5": "1b61b9991a7b7379955d5ef4d5a3b7e4"
        }
      ]
    }
  ]
}