{
  "formatVersion": "1.1",
  "component": {
    "url": "../../adaptive-layout/9999.0.0-SNAPSHOT/adaptive-layout-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.material3.adaptive",
    "module": "adaptive-layout",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "adaptive-layout-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "adaptive-layout-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 315451,
          "sha512": "0e180ed83e73098020a5aea3594d02ff090119758e9517147c63d3c870525d4df1f405378577b33571c2400e5fb34ff4c24baae98fe7e3df93b000cd1f977ea4",
          "sha256": "f33b08b414bb8df0da48100ee02eedae8af895b75b6d4bf8c18c63758f38b6b2",
          "sha1": "f9d53f0facb474d4f1c7b7c73a800704799f5541",
          "md5": "0717191f30bb8a938fd25bf45f4b2acd"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "adaptive-layout-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "adaptive-layout-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 315451,
          "sha512": "0e180ed83e73098020a5aea3594d02ff090119758e9517147c63d3c870525d4df1f405378577b33571c2400e5fb34ff4c24baae98fe7e3df93b000cd1f977ea4",
          "sha256": "f33b08b414bb8df0da48100ee02eedae8af895b75b6d4bf8c18c63758f38b6b2",
          "sha1": "f9d53f0facb474d4f1c7b7c73a800704799f5541",
          "md5": "0717191f30bb8a938fd25bf45f4b2acd"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "adaptive-layout-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "url": "adaptive-layout-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "size": 67782,
          "sha512": "11f92d79ca20de5c819fa340c6da19d59aa2184213f9f4963c89e471ed3fd6536a380c2037197607d4972aa51098b2741ab44e81d5535e3cc76096c041598903",
          "sha256": "f63b129807386425d7cf6febebe87aebbbdf8d08d3dd565caa5a0abdfb41c797",
          "sha1": "615b9d8a328392b1ecfa526a061c8461aa270327",
          "md5": "3ca5a7cd471f2cfd798a7e19d0a1e904"
        }
      ]
    }
  ]
}