{
  "formatVersion": "1.1",
  "component": {
    "url": "../../savedstate/9999.0.0-SNAPSHOT/savedstate-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.androidx.savedstate",
    "module": "savedstate",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "savedstate-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 96452,
          "sha512": "597be6bbfd88235f4055e360673a33aabc4076be083a849a518250339f78f153a7a8649eb5cca916c3dac6542898c0e565b93fbbc3b7bdd58e09c4e8bf8ca24a",
          "sha256": "a24f03cb5df0568b278cebbb357a8e65c9149ba7eaec3a62c9e6b101fdf9c52e",
          "sha1": "fb93e84e1ecd9227acec0ae80abeeeb9c46f81b7",
          "md5": "34f3a079e30f94159e34b98aa4710e42"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "savedstate-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 96452,
          "sha512": "597be6bbfd88235f4055e360673a33aabc4076be083a849a518250339f78f153a7a8649eb5cca916c3dac6542898c0e565b93fbbc3b7bdd58e09c4e8bf8ca24a",
          "sha256": "a24f03cb5df0568b278cebbb357a8e65c9149ba7eaec3a62c9e6b101fdf9c52e",
          "sha1": "fb93e84e1ecd9227acec0ae80abeeeb9c46f81b7",
          "md5": "34f3a079e30f94159e34b98aa4710e42"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "savedstate-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "url": "savedstate-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "size": 39202,
          "sha512": "ae8c38e0f9de54b5515729a713eafb0b11d524a52b853f4f897ce07c58cd225bdb4b19001e88aa6d95d05bf3207b12c542b895f85187da02b5f3ad07051af2d1",
          "sha256": "49d32bdc62742a7ca1bf2be73ceb950af4b93b950ee2a97c1b1cae814cdbaa37",
          "sha1": "50a96e72ddf55cde94b26697d52634ec8077e4d7",
          "md5": "d7d0e574a3fd79b30adfec9cc3e75e84"
        }
      ]
    }
  ]
}