{
  "formatVersion": "1.1",
  "component": {
    "url": "../../adaptive/9999.0.0-SNAPSHOT/adaptive-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.material3.adaptive",
    "module": "adaptive",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "adaptive-macosArm64Main-9999.0.0-SNAPSHOT.klib",
          "url": "adaptive-macosarm64-9999.0.0-SNAPSHOT.klib",
          "size": 19717,
          "sha512": "f6d8d954d71ec7ec74cf47aabecfcbb2e5cf6daee3aee4a59dab0714a452c529eeb6d1067f7decb32b1bec16ab2f4d5d1bedd086abb6b343650725b60bec40a4",
          "sha256": "75d739926d2bec66962de6239aa8a50e44a4709c9eb2411bd573bd26dbf19518",
          "sha1": "816ca6c644906a91407cdd9ac0f4a248e8be7576",
          "md5": "5bc5ccac748a2be26346e6147a8bd209"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "adaptive-macosarm64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "adaptive-macosarm64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 7579,
          "sha512": "87a9d2b75935aeec2c43db051657f135490063d5bb50ac35e457ee80f3a7dafdc718b4caa11f0aba99e2f67a2dec2b66f2a480b7dbaf5dfa60cc274d39c0b01f",
          "sha256": "c32dcea1cd1cc0b2f5b4bcd3d5d81a11ef123275c2692ba4f687631d53e50860",
          "sha1": "7c47642ef0ff20e4ce0ae6f529217d0a7ffc76af",
          "md5": "a083682ea78e440c9b6d9e2b8eca7788"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "adaptive-macosarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "url": "adaptive-macosarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}