{
  "formatVersion": "1.1",
  "component": {
    "url": "../../window-core/9999.0.0-SNAPSHOT/window-core-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.androidx.window",
    "module": "window-core",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "window-core-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "window-core-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 19947,
          "sha512": "297b47f6cdae66122fc23cb012af13b58a722815d2b95b14ab8fc374f8cdb330b6ed2e57461701bdcacf921a6f4f8e89d74289ba1e0d87b844ef9385b4a2dc99",
          "sha256": "c1923ceb765c5a2aa1d4d9187051655e69e53d74b52ff9f6b307745ebfbb0202",
          "sha1": "f7f52714bb43e31cffe6caeaffba9133ab7a91fd",
          "md5": "41f4ef970ac88a7907cc22c7c20f7401"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "window-core-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "window-core-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 19947,
          "sha512": "297b47f6cdae66122fc23cb012af13b58a722815d2b95b14ab8fc374f8cdb330b6ed2e57461701bdcacf921a6f4f8e89d74289ba1e0d87b844ef9385b4a2dc99",
          "sha256": "c1923ceb765c5a2aa1d4d9187051655e69e53d74b52ff9f6b307745ebfbb0202",
          "sha1": "f7f52714bb43e31cffe6caeaffba9133ab7a91fd",
          "md5": "41f4ef970ac88a7907cc22c7c20f7401"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "window-core-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "url": "window-core-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "size": 8804,
          "sha512": "ae70222feba801a749b9c9498250c034d6ef44bfabc2edbce34503b0492fe6c7a2f2c0c0a62071cffc7b3aaa48dacbebcb44bf12a96375d60a61c7c58ee68ce5",
          "sha256": "7f12a1dfe66bf3f3d0f68395b1f749377e533cdd245dffa3465e07d5acc0536e",
          "sha1": "37942415b980a2d51e646603b246932976db31b8",
          "md5": "07828aa7ba8527c29503ee6042e34503"
        }
      ]
    }
  ]
}