{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material3-adaptive-navigation-suite/9999.0.0-SNAPSHOT/material3-adaptive-navigation-suite-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.material3",
    "module": "material3-adaptive-navigation-suite",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "material3-adaptive-navigation-suite-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "material3-adaptive-navigation-suite-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 60105,
          "sha512": "da465de3e578face37c563c7f490a90eb8332289616bfeb25d9375e3cbd001251bb75e4a5c63d1cd58773a7edd82b7da29b89f848f4b244e2e63a13357a5b6ed",
          "sha256": "fd0b707add17bdeb7ace0f239cffe39adcdd62baca60a488a3dcb3cce5530f58",
          "sha1": "5ef843b41495199772a3396122bf64e8dd87ba14",
          "md5": "fda52dc612a46bdd1083c32d5099616c"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "material3-adaptive-navigation-suite-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "material3-adaptive-navigation-suite-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 60105,
          "sha512": "da465de3e578face37c563c7f490a90eb8332289616bfeb25d9375e3cbd001251bb75e4a5c63d1cd58773a7edd82b7da29b89f848f4b244e2e63a13357a5b6ed",
          "sha256": "fd0b707add17bdeb7ace0f239cffe39adcdd62baca60a488a3dcb3cce5530f58",
          "sha1": "5ef843b41495199772a3396122bf64e8dd87ba14",
          "md5": "fda52dc612a46bdd1083c32d5099616c"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "material3-adaptive-navigation-suite-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "url": "material3-adaptive-navigation-suite-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "size": 8869,
          "sha512": "20e9ecfeb003d86c76b45b71f1f444769b3484ca52ff05248fa441d0b53c1002646b4168fd508e0348a3fe2eeeeadcc43a569d15ae0a27f7c660b09840f85e96",
          "sha256": "81a8cd3e5e2ac725df6c951803da02e2f88269292208d92073b0e013080e8ab6",
          "sha1": "827b85ce67919df0f7a9d174a79abdc509585fdd",
          "md5": "97782a2538cf90364472bdbdb082ca05"
        }
      ]
    }
  ]
}