{
  "formatVersion": "1.1",
  "component": {
    "url": "../../animation-core/9999.0.0-SNAPSHOT/animation-core-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.animation",
    "module": "animation-core",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-js-9999.0.0-SNAPSHOT.klib",
          "url": "animation-core-js-9999.0.0-SNAPSHOT.klib",
          "size": 445409,
          "sha512": "8e527e6e736d088d52f546edbf91824a62405e6e7786c89828ac0bff7f69d44ef647731e55d14f5543fcd71ea86a0c26e46829574da26a2525e85bd1539c0c64",
          "sha256": "8c1b02f5c85e02578f436b5d8e38a8c08e0c309a573473b875e39a81d2340b2c",
          "sha1": "e5fb67b7a1b1f7e95275e32e9a869b633b98fe95",
          "md5": "b88a61671b0e3de865f2194ecaa05b59"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlinx-atomicfu-runtime",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-js-9999.0.0-SNAPSHOT.klib",
          "url": "animation-core-js-9999.0.0-SNAPSHOT.klib",
          "size": 445409,
          "sha512": "8e527e6e736d088d52f546edbf91824a62405e6e7786c89828ac0bff7f69d44ef647731e55d14f5543fcd71ea86a0c26e46829574da26a2525e85bd1539c0c64",
          "sha256": "8c1b02f5c85e02578f436b5d8e38a8c08e0c309a573473b875e39a81d2340b2c",
          "sha1": "e5fb67b7a1b1f7e95275e32e9a869b633b98fe95",
          "md5": "b88a61671b0e3de865f2194ecaa05b59"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "animation-core-js-9999.0.0-SNAPSHOT-sources.jar",
          "url": "animation-core-js-9999.0.0-SNAPSHOT-sources.jar",
          "size": 111735,
          "sha512": "de342812a3f683a748f789630baf767220fe36bd50222c1e0708917c130205bacfc36759b7f101f2cc17688eb6b3524a860e15dd450dc874aa38db32f2e2802a",
          "sha256": "3e5139f01715c1f7a118884fbdddbfa9a3dc47ef2f5df6dfa81081ca988b8cd3",
          "sha1": "30de17e1f737583fdb3879b75f655ce0d36bc3b6",
          "md5": "f9de1fc56fece1d0973ebb2584a429a0"
        }
      ]
    }
  ]
}