{
  "formatVersion": "1.1",
  "component": {
    "url": "../../savedstate/9999.0.0-SNAPSHOT/savedstate-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.androidx.savedstate",
    "module": "savedstate",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-js-9999.0.0-SNAPSHOT.klib",
          "url": "savedstate-js-9999.0.0-SNAPSHOT.klib",
          "size": 96446,
          "sha512": "599b413175cf2fb12fdeda5dbbad40146f398afa5a51e6f3a4be290daac4b081f9eb5500279ca26a10d4fc2b465367993a9cf59f9f1efc209783c3a8c687480a",
          "sha256": "bc37b9237a41794530c68d4ef0b4f5e3d819f9fb61f0cee16f80619203fb3764",
          "sha1": "c79c01365466b04752e89808df81c66e04e0be23",
          "md5": "f71a9a99845db42f3d7b3752d5ac0ab8"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-js-9999.0.0-SNAPSHOT.klib",
          "url": "savedstate-js-9999.0.0-SNAPSHOT.klib",
          "size": 96446,
          "sha512": "599b413175cf2fb12fdeda5dbbad40146f398afa5a51e6f3a4be290daac4b081f9eb5500279ca26a10d4fc2b465367993a9cf59f9f1efc209783c3a8c687480a",
          "sha256": "bc37b9237a41794530c68d4ef0b4f5e3d819f9fb61f0cee16f80619203fb3764",
          "sha1": "c79c01365466b04752e89808df81c66e04e0be23",
          "md5": "f71a9a99845db42f3d7b3752d5ac0ab8"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "savedstate-js-9999.0.0-SNAPSHOT-sources.jar",
          "url": "savedstate-js-9999.0.0-SNAPSHOT-sources.jar",
          "size": 39202,
          "sha512": "ae8c38e0f9de54b5515729a713eafb0b11d524a52b853f4f897ce07c58cd225bdb4b19001e88aa6d95d05bf3207b12c542b895f85187da02b5f3ad07051af2d1",
          "sha256": "49d32bdc62742a7ca1bf2be73ceb950af4b93b950ee2a97c1b1cae814cdbaa37",
          "sha1": "50a96e72ddf55cde94b26697d52634ec8077e4d7",
          "md5": "d7d0e574a3fd79b30adfec9cc3e75e84"
        }
      ]
    }
  ]
}