{
  "formatVersion": "1.1",
  "component": {
    "url": "../../navigation-common/9999.0.0-SNAPSHOT/navigation-common-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.androidx.navigation",
    "module": "navigation-common",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-tvosArm64Main-9999.0.0-SNAPSHOT.klib",
          "url": "navigation-common-tvosarm64-9999.0.0-SNAPSHOT.klib",
          "size": 314355,
          "sha512": "10c9faf915887e66c3854bc236750a5c2106a6d3aaccfa526714c44c6999417535a84c54bb96c034f01418386621317834a279552901cc0184fa510961a46c69",
          "sha256": "9af526c15717fb62ec3f6c7011af20fabb52b46b3f510febf76c28a717d96c2e",
          "sha1": "3ac40b5dd61c4fa6a87546559c062674a606eb4a",
          "md5": "997c15fbf1a5f3b2030860116ebd4b4b"
        }
      ]
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "navigation-common-tvosarm64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "navigation-common-tvosarm64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 102535,
          "sha512": "a733f2c683eaf205d97098bea9fd740a79f9dd933fae001f28ad290fcd0105d7918fcde8011af927a67116d2cfff95568f1be5a027f8e7a3694a8f2f6dd42d14",
          "sha256": "0e76c39666769438b719800caf2028ed1b1640cb28a6c36a4fba031a24beed4c",
          "sha1": "f2a19d5405caab53812696f4ea64b33e8a4d709a",
          "md5": "c1d2f0d673b4d359a3f0c35ddf10dc2c"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-tvosarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "url": "navigation-common-tvosarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "size": 3852,
          "sha512": "1f9a1990213911031525b8fd9a623d6f0de9f0c8d614b625266debe9d4a3df3d998d6b86f9be8c4b1a896d51d6097ded8796771280084b88a7d72f07bbad3276",
          "sha256": "7ad910e50e37a0d374339c5c2eed97f577a39c795fd16b308c22cce84b92407c",
          "sha1": "1fd92ecf4295f57ea1735a43d9c945ed20409cc6",
          "md5": "f9a0e6b939f1a6fbf3cdb1297af9859b"
        }
      ]
    }
  ]
}