{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-graphics/9999.0.0-SNAPSHOT/ui-graphics-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-graphics",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.9.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-macosX64Main-9999.0.0-SNAPSHOT.klib",
          "url": "ui-graphics-macosx64-9999.0.0-SNAPSHOT.klib",
          "size": 659319,
          "sha512": "7d9f973d6d18c5954a811f643034bbf317d2ea014b5f8fb03b9e63a79537b045288476bc027ea6f1f9ced2c40ad3abf2cdcfc3fcc00203c7d7533121b7ab0d56",
          "sha256": "a7cbc51241c94c5e8d42a74e88dc7e96c3a3c6680af43e28c0d5258fa6147f82",
          "sha1": "d12870b5f66dcf8431fbef283b2fc42dc432f5cf",
          "md5": "25498229b42ff8da8fe0db00e2b4b78b"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-graphics-macosx64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "ui-graphics-macosx64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 224261,
          "sha512": "45064788dd3a5b0a838a8b7b5ab01c3f8a434ad8412aac6f85d999b04ac4bbdff0260e02d3b1ce74784dffb666c20d3a6bfaa0f7804dc9fce7ac302dfee84504",
          "sha256": "722e565b51b59f87a401262c0d40f86257141a2c8a811e59b11770b63ce51bc8",
          "sha1": "5c09fe342582303c35a1bc3eea4d2cf484f52528",
          "md5": "5fe02b16545f4911a968efb170e3ef88"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.9.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-macosx64-9999.0.0-SNAPSHOT-metadata.jar",
          "url": "ui-graphics-macosx64-9999.0.0-SNAPSHOT-metadata.jar",
          "size": 4297,
          "sha512": "e28cc17acccc0eb1eeffa49fd5b31dc6a57d6974dcae0c46f89d95905801cdf2fa1eb2ab399a636d920c7ff8455e0ea025e2d380156ec3231580dc1fd9d00877",
          "sha256": "214c5bbcfa801a70b89e1243c9ab5b384ecb32aab242b9e4e9323fda689431bb",
          "sha1": "a8644641975aa3f647d2f4db66efbecc0c599a8b",
          "md5": "d5d68e55cdaf0e62d712f88261fc938e"
        }
      ]
    }
  ]
}