{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/9999.0.0-SNAPSHOT/runtime-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.runtime",
    "module": "runtime",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-linuxX64Main-9999.0.0-SNAPSHOT.klib",
          "url": "runtime-linuxx64-9999.0.0-SNAPSHOT.klib",
          "size": 1688619,
          "sha512": "56b0481410ae151b39316b7a4489be440e7a282d80cc1352235118f7f92c46223bb50ee71ca9624121f8ba152e7270ef64437799347d3491a05c96c25562859b",
          "sha256": "6cd01923263b62973c5bfc2877bf33dab9b009d425e20fc29a8b7e2e3da87d9c",
          "sha1": "495f4fe7fc1948f33ffb771d195394c992d2ca9b",
          "md5": "6965ee72aaffa9c6ac90b5bdb0403b32"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "runtime-linuxx64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "runtime-linuxx64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 417713,
          "sha512": "38adcddb28b0c3e8107f2d52dd43df8ecdde85b5c4cd5fe6c3a2239562c8bdc8820ec7e45d56fc53ecc8b05b45e42e81a7374b48a06052523f472fe44ec3c667",
          "sha256": "5e726d1d0e2ddd00a29a93c7b01a93e6c067a451b08cf2e115755432ae4a4e18",
          "sha1": "1b9b353247e7c5d16c89c33cffb6c25ff7fc8cdf",
          "md5": "6585da68b2f3b5f9cdb230033d8d205b"
        }
      ]
    }
  ]
}