{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-graphics/9999.0.0-SNAPSHOT/ui-graphics-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-graphics",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.9.3"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "ui-graphics-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 660964,
          "sha512": "d7a3c9da059c86aa72b0a04918c75c58bf4103098fa1b4d4f1261e895bbc851a6f00f2148fb3488fb195d641d5dc230cc0120ef5720562587bbb4ce64ddcd4f2",
          "sha256": "086b7ca0e27a733d14eccf841737df5137479782eee3797e2ec317da5b80fa68",
          "sha1": "958d089ad1610733d2fd7e3395652210b17d0e71",
          "md5": "9274dff48739c135088a4a222a70cb56"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.9.3"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko-js-wasm-runtime",
          "version": {
            "requires": "0.9.3"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko-wasm-js",
          "version": {
            "requires": "0.9.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "ui-graphics-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 660964,
          "sha512": "d7a3c9da059c86aa72b0a04918c75c58bf4103098fa1b4d4f1261e895bbc851a6f00f2148fb3488fb195d641d5dc230cc0120ef5720562587bbb4ce64ddcd4f2",
          "sha256": "086b7ca0e27a733d14eccf841737df5137479782eee3797e2ec317da5b80fa68",
          "sha1": "958d089ad1610733d2fd7e3395652210b17d0e71",
          "md5": "9274dff48739c135088a4a222a70cb56"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "ui-graphics-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "url": "ui-graphics-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "size": 223974,
          "sha512": "486666d925a95341ba07167ac47270a3031bd7b67db2507436596ba1d423e190e4854cb4e473cb84a84cc99f072d1d3b53c4e1669304b275d5f32a346598f42f",
          "sha256": "c5d90d314ebc1b09edda0ecd664bb1e2b8499690c791cdc4a0a8a9053dd36520",
          "sha1": "c4002beda9f6bfb356509d6f83e22443a1eccf11",
          "md5": "7d2beb0fac9eb05b620e131e16126de8"
        }
      ]
    }
  ]
}