{
  "formatVersion": "1.1",
  "component": {
    "url": "../../savedstate/9999.0.0-SNAPSHOT/savedstate-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.androidx.savedstate",
    "module": "savedstate",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "savedstate-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 90385,
          "sha512": "80ba9b7254dfd4d753ed5e55744439bc7c3c207f9908566c985c69ed812aa51383b54c88cdf36a88f2474d0ae08a45dec19071535b34f00f8a6912d993d8207b",
          "sha256": "33ebd0043da8c14b19b83f97549dc9bf8b78773fec839361718c6068809c384f",
          "sha1": "68b36ccb05083e1283bba1a9284440d6d35c746d",
          "md5": "02da7eb5a943bd55f8322f4cbfd51492"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "savedstate-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 90385,
          "sha512": "80ba9b7254dfd4d753ed5e55744439bc7c3c207f9908566c985c69ed812aa51383b54c88cdf36a88f2474d0ae08a45dec19071535b34f00f8a6912d993d8207b",
          "sha256": "33ebd0043da8c14b19b83f97549dc9bf8b78773fec839361718c6068809c384f",
          "sha1": "68b36ccb05083e1283bba1a9284440d6d35c746d",
          "md5": "02da7eb5a943bd55f8322f4cbfd51492"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "savedstate-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "url": "savedstate-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "size": 33884,
          "sha512": "6c1e589bc464a16f3f349f1b5c901609938fbeb2ac3eac48d5a77bcb153a4fb5646b98400629a83144cffa5d38d3244befaa69f39680e676eda895ef3a65f8fd",
          "sha256": "611a1152627f0720faeb67f2b99821b784b85f3d41b1519f16f31b38d0193bfa",
          "sha1": "37f697a351ee73961f22b309722544b846d3175e",
          "md5": "660d146cdea41eea85dfe0cd3e41b4a1"
        }
      ]
    }
  ]
}