{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.material3.adaptive",
    "module": "adaptive-navigation",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "adaptive-navigation-9999.0.0-SNAPSHOT.jar",
          "url": "adaptive-navigation-9999.0.0-SNAPSHOT.jar",
          "size": 6882,
          "sha512": "c0c086f127ac523b68808b579f2475ec89c3132429ac77d3d198ead82d8433ae7c1b80339f9cce172315d744fbfbad7c8afb4ed77d80dbb650375b05a850e3c5",
          "sha256": "5308253f991b4c13fb60d2b12bed64c8e9f4d1371583ef7d87154808f13e9ebe",
          "sha1": "87a350e8feb2bd90a1a0796eddccbb36606526d0",
          "md5": "6a0f7e01632476562829d2527c9d6495"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "adaptive-navigation-9999.0.0-SNAPSHOT-sources.jar",
          "url": "adaptive-navigation-9999.0.0-SNAPSHOT-sources.jar",
          "size": 6825,
          "sha512": "2e80868b2283118d306c78cc32f04e37e0fe2fdd01baa9eb5ded769e13a00ae1a7d938bbccbac97ecaa64244e81efa1b22848bb02a9220b200027b8627e7afd6",
          "sha256": "d5e7ffdb3747e465629a8143991a1dbf94e989e7ca3e5041903d24053a203235",
          "sha1": "973557ed783ee8b55dc5418e41629a8eccb55b16",
          "md5": "49eecdac2a5b77e212d5869b348a2ab2"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-navigation",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-navigation",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ]
    },
    {
      "name": "debugSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-navigation",
          "version": {
            "requires": "1.1.0-beta01"
          }
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-navigation",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-navigation",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-navigation",
          "version": {
            "requires": "1.1.0-beta01"
          }
        }
      ]
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../adaptive-navigation-desktop/9999.0.0-SNAPSHOT/adaptive-navigation-desktop-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3.adaptive",
        "module": "adaptive-navigation-desktop",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../adaptive-navigation-desktop/9999.0.0-SNAPSHOT/adaptive-navigation-desktop-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3.adaptive",
        "module": "adaptive-navigation-desktop",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../adaptive-navigation-desktop/9999.0.0-SNAPSHOT/adaptive-navigation-desktop-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3.adaptive",
        "module": "adaptive-navigation-desktop",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../adaptive-navigation-js/9999.0.0-SNAPSHOT/adaptive-navigation-js-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3.adaptive",
        "module": "adaptive-navigation-js",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../adaptive-navigation-js/9999.0.0-SNAPSHOT/adaptive-navigation-js-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3.adaptive",
        "module": "adaptive-navigation-js",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../adaptive-navigation-js/9999.0.0-SNAPSHOT/adaptive-navigation-js-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3.adaptive",
        "module": "adaptive-navigation-js",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../adaptive-navigation-macosarm64/9999.0.0-SNAPSHOT/adaptive-navigation-macosarm64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3.adaptive",
        "module": "adaptive-navigation-macosarm64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../adaptive-navigation-macosarm64/9999.0.0-SNAPSHOT/adaptive-navigation-macosarm64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3.adaptive",
        "module": "adaptive-navigation-macosarm64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../adaptive-navigation-macosarm64/9999.0.0-SNAPSHOT/adaptive-navigation-macosarm64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3.adaptive",
        "module": "adaptive-navigation-macosarm64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../adaptive-navigation-macosx64/9999.0.0-SNAPSHOT/adaptive-navigation-macosx64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3.adaptive",
        "module": "adaptive-navigation-macosx64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../adaptive-navigation-macosx64/9999.0.0-SNAPSHOT/adaptive-navigation-macosx64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3.adaptive",
        "module": "adaptive-navigation-macosx64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../adaptive-navigation-macosx64/9999.0.0-SNAPSHOT/adaptive-navigation-macosx64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3.adaptive",
        "module": "adaptive-navigation-macosx64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "uikitArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../adaptive-navigation-uikitarm64/9999.0.0-SNAPSHOT/adaptive-navigation-uikitarm64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3.adaptive",
        "module": "adaptive-navigation-uikitarm64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "uikitArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../adaptive-navigation-uikitarm64/9999.0.0-SNAPSHOT/adaptive-navigation-uikitarm64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3.adaptive",
        "module": "adaptive-navigation-uikitarm64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "uikitArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../adaptive-navigation-uikitarm64/9999.0.0-SNAPSHOT/adaptive-navigation-uikitarm64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3.adaptive",
        "module": "adaptive-navigation-uikitarm64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "uikitSimArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../adaptive-navigation-uikitsimarm64/9999.0.0-SNAPSHOT/adaptive-navigation-uikitsimarm64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3.adaptive",
        "module": "adaptive-navigation-uikitsimarm64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "uikitSimArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../adaptive-navigation-uikitsimarm64/9999.0.0-SNAPSHOT/adaptive-navigation-uikitsimarm64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3.adaptive",
        "module": "adaptive-navigation-uikitsimarm64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "uikitSimArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../adaptive-navigation-uikitsimarm64/9999.0.0-SNAPSHOT/adaptive-navigation-uikitsimarm64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3.adaptive",
        "module": "adaptive-navigation-uikitsimarm64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "uikitX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../adaptive-navigation-uikitx64/9999.0.0-SNAPSHOT/adaptive-navigation-uikitx64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3.adaptive",
        "module": "adaptive-navigation-uikitx64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "uikitX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../adaptive-navigation-uikitx64/9999.0.0-SNAPSHOT/adaptive-navigation-uikitx64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3.adaptive",
        "module": "adaptive-navigation-uikitx64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "uikitX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../adaptive-navigation-uikitx64/9999.0.0-SNAPSHOT/adaptive-navigation-uikitx64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3.adaptive",
        "module": "adaptive-navigation-uikitx64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../adaptive-navigation-wasm-js/9999.0.0-SNAPSHOT/adaptive-navigation-wasm-js-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3.adaptive",
        "module": "adaptive-navigation-wasm-js",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../adaptive-navigation-wasm-js/9999.0.0-SNAPSHOT/adaptive-navigation-wasm-js-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3.adaptive",
        "module": "adaptive-navigation-wasm-js",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../adaptive-navigation-wasm-js/9999.0.0-SNAPSHOT/adaptive-navigation-wasm-js-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.material3.adaptive",
        "module": "adaptive-navigation-wasm-js",
        "version": "9999.0.0-SNAPSHOT"
      }
    }
  ]
}