{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material3-common/9999.0.0-SNAPSHOT/material3-common-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.material3.common",
    "module": "material3-common",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "material3-common-desktop-9999.0.0-SNAPSHOT.jar",
          "url": "material3-common-desktop-9999.0.0-SNAPSHOT.jar",
          "size": 41937,
          "sha512": "065c2737a6eb0f3369b7f19a33f025bccabe84ce8d2375b079b8d67d3fab24353a7a2de8dc9d46ec58f6e7acc66b6409ed9273caa1cee7cd46293ed1a1ae8eed",
          "sha256": "04f6330d55298c1bc4d82d4e49be20658bcb811fd3df004fb0d9d1168ca1964e",
          "sha1": "47d606d02674634e454e5b1f8a93f86bcbff95e6",
          "md5": "4b9c89fbd4eeddc9edc84bac3be4a171"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "material3-common-desktop-9999.0.0-SNAPSHOT.jar",
          "url": "material3-common-desktop-9999.0.0-SNAPSHOT.jar",
          "size": 41937,
          "sha512": "065c2737a6eb0f3369b7f19a33f025bccabe84ce8d2375b079b8d67d3fab24353a7a2de8dc9d46ec58f6e7acc66b6409ed9273caa1cee7cd46293ed1a1ae8eed",
          "sha256": "04f6330d55298c1bc4d82d4e49be20658bcb811fd3df004fb0d9d1168ca1964e",
          "sha1": "47d606d02674634e454e5b1f8a93f86bcbff95e6",
          "md5": "4b9c89fbd4eeddc9edc84bac3be4a171"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "material3-common-desktop-9999.0.0-SNAPSHOT-sources.jar",
          "url": "material3-common-desktop-9999.0.0-SNAPSHOT-sources.jar",
          "size": 12940,
          "sha512": "2029ffc0277024a834bce0789b01c58dc798e1401c30d76ad319ff47bc6a7e441aefe1d8e07a5d15aeace298fbfc60375e9e3a130620c0bfe1a9ba24a3a99016",
          "sha256": "a4f2297acf8a5a2749395fc33f61cb57b561fefb100d1c8b1163086e41df36a0",
          "sha1": "aa019a4722dc8fea34d478cacd92f0ea006a7132",
          "md5": "19fdd66e10756d078e011f116506b3db"
        }
      ]
    }
  ]
}