{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lifecycle-viewmodel-savedstate/9999.0.0-SNAPSHOT/lifecycle-viewmodel-savedstate-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.androidx.lifecycle",
    "module": "lifecycle-viewmodel-savedstate",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-js-9999.0.0-SNAPSHOT.klib",
          "url": "lifecycle-viewmodel-savedstate-js-9999.0.0-SNAPSHOT.klib",
          "size": 42948,
          "sha512": "cff18eab6ab8cb005e5cf5cfb70cf6d1855a3e8fff8ca79ce3b45eea19a61482f9d3e44af45800429843ed8328d22c857d4e64692a18d1878970cca96123b01a",
          "sha256": "580d7ad459a8f97fa32bb138a5545ef26389307cbdba3dff1b8b387c1f3c6f22",
          "sha1": "7eab047d89dcf8ef6bcc97c761cf1db593149711",
          "md5": "c54412d403a9cd31e9023aef04960157"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-js-9999.0.0-SNAPSHOT.klib",
          "url": "lifecycle-viewmodel-savedstate-js-9999.0.0-SNAPSHOT.klib",
          "size": 42948,
          "sha512": "cff18eab6ab8cb005e5cf5cfb70cf6d1855a3e8fff8ca79ce3b45eea19a61482f9d3e44af45800429843ed8328d22c857d4e64692a18d1878970cca96123b01a",
          "sha256": "580d7ad459a8f97fa32bb138a5545ef26389307cbdba3dff1b8b387c1f3c6f22",
          "sha1": "7eab047d89dcf8ef6bcc97c761cf1db593149711",
          "md5": "c54412d403a9cd31e9023aef04960157"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-js-9999.0.0-SNAPSHOT-sources.jar",
          "url": "lifecycle-viewmodel-savedstate-js-9999.0.0-SNAPSHOT-sources.jar",
          "size": 19716,
          "sha512": "f70507a3b3fdf2a2696c3e8eb7ddc7134af20c3b0a59035ce610e5adcea41f822cd6ea52ccfb0eeb8230f83520e23211033bde5e2397c769e8f7de0b8fada424",
          "sha256": "f8b7f51c614cb013186b7fd99bb5de5bb82c55c84a8d30b6f84cdb1da1e77f07",
          "sha1": "120a3602d9828ecd99615a2191c3787d4f9b490f",
          "md5": "30e0055a85d12fa8e00b963375f49bc1"
        }
      ]
    }
  ]
}