{
  "formatVersion": "1.1",
  "component": {
    "url": "../../animation/9999.0.0-SNAPSHOT/animation-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.animation",
    "module": "animation",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "uikitX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "animation-uikitX64Main-9999.0.0-SNAPSHOT.klib",
          "url": "animation-uikitx64-9999.0.0-SNAPSHOT.klib",
          "size": 359019,
          "sha512": "51b2aabc9db6505f5517fd5cf5d85b47343740b74524837b086a767bb9ad3dc0ddce9fd57e923f76de70917be15637ff69c97de692cfb78c63d2223c62597a02",
          "sha256": "aad4602b3e3576b6326128a292403c9ad19724549e453094d620b531373f76b9",
          "sha1": "d31321585cc7d6ef5ce3466e1fe427b8d96abce0",
          "md5": "f9d2abd8b34ff6b640af5218eb6ba293"
        }
      ]
    },
    {
      "name": "uikitX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "animation-uikitx64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "animation-uikitx64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 77241,
          "sha512": "fc2220abe0c863fc0e17f1665c2533ba142fa619bd54a6c5175be84a27b4c09ea074f7a7ab13759e239f7032806c7e6b3596256ce2b3a2da2a0e756cb8c2fe60",
          "sha256": "777189dd91599eb558799a835486806533e12bbeb38f301f8d10f65d62d96fe4",
          "sha1": "0701d11476b2f45a8013ac964e45aed911ef63e7",
          "md5": "34f86b9a7aab627263c0ff3c370b8471"
        }
      ]
    },
    {
      "name": "uikitX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "animation-uikitx64-9999.0.0-SNAPSHOT-metadata.jar",
          "url": "animation-uikitx64-9999.0.0-SNAPSHOT-metadata.jar",
          "size": 3983,
          "sha512": "3e0f4c67c7fae45176afc46ef70b9b3c5aa4ce78b2ffe34cbf6482e636aaee2fb08aa8fa12012f2285412c19d3545dff928a8f26e8c571e123c53e02b6ae2d9d",
          "sha256": "ac99532051a982c7e19d97b7a5d4dc368186a2a4cc9bc7cf3426c367802b8372",
          "sha1": "95e2f3ef47b9c6664ebad9f81735a63fe5816074",
          "md5": "11992664afd8b09149fac0b04aa0c92c"
        }
      ]
    }
  ]
}