{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/9999.0.0-SNAPSHOT/runtime-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.runtime",
    "module": "runtime",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-mingwX64Main-9999.0.0-SNAPSHOT.klib",
          "url": "runtime-mingwx64-9999.0.0-SNAPSHOT.klib",
          "size": 1682504,
          "sha512": "8b04e78e2077e2561756e718b1ef81806909e2a4cf18e20b2f0c3af2c87ff9c0b6d5277c1f8471c008c363a9121150428e0487a7d8c0a49c3db5368859ac3e89",
          "sha256": "63daf0a8b5f489d34c1cd61e1e5e2e6db53397da418221f4de721f2c8ec37679",
          "sha1": "ec785cc1be1657ce82f8ae758ad1defa114e1830",
          "md5": "0a673f6f2c697d6a715d3e64b290e596"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "runtime-mingwx64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "runtime-mingwx64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 415648,
          "sha512": "020d1bef75290cdffad465458032f1dcb5cb0e4d4b8af8c6c24abb737335febf1aaf0c9f15bcf628774326e76b0318c0b876c7aa2be0ade7accefedf8a2a8645",
          "sha256": "cbe2e98332869883c73285ded36dfd61ac0db6c87c3d006205f33f82387819ff",
          "sha1": "2dfd4b1ac4b18f81953b6d4525f7c6640af8dbc0",
          "md5": "26aa91f666b1a2b41339e5da2c0ccea0"
        }
      ]
    }
  ]
}