{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lifecycle-viewmodel-compose/9999.0.0-SNAPSHOT/lifecycle-viewmodel-compose-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.androidx.lifecycle",
    "module": "lifecycle-viewmodel-compose",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-macosArm64Main-9999.0.0-SNAPSHOT.klib",
          "url": "lifecycle-viewmodel-compose-macosarm64-9999.0.0-SNAPSHOT.klib",
          "size": 25299,
          "sha512": "34a3b74173dece6662362c13cff4b7d3744f85b91b3de548223c985da5b3a563da9ab390124a71dd1d02fdb127edb1af55c503acbc0126ba1fd9a5bdbafef487",
          "sha256": "9dd97fc9a57459f9af6d0a5f46ac9e440f149184afe86f383b2d811cf7cea11c",
          "sha1": "bccea008fdc1b4356b9d0e34ee2290b7f8d4cc03",
          "md5": "c429f8518937cacf67eb7831db57cf30"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-macosarm64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "lifecycle-viewmodel-compose-macosarm64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 9595,
          "sha512": "fcd870096fb9df65e80e5ba46c2ec216f68c49997f8a3b2ee8d774cc8b2f094cb8c7bac3f1d989a84847ba86256a13fc0bf4f0a628fa19da633a2734fb5fff6c",
          "sha256": "aa4a4b894c173a9ac1cc0012c7a78069ebca082baedd8991a29db803ed5408ed",
          "sha1": "0a93d56d730a9ddcb5a1a56e8be57f65521d7730",
          "md5": "4a5a7b55d9375b793317187ad2e275eb"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-macosarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "url": "lifecycle-viewmodel-compose-macosarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "size": 4407,
          "sha512": "34b52bf0ef062627d5a1b539692e4216005fb78cc420ec6b7ffde3e54efc6cf850fbdb56f9300a313752a9f98806b7c0cd31436f2e738ef7db29c682b1b50e31",
          "sha256": "cd694a1b8f90cf0ff5d7b482d93fcd097e195dbc4dbf906e69f7cf20c0690437",
          "sha1": "ac19bf2d0cc6860f92f5b848fd3c6a45af215b21",
          "md5": "cde6160a5d8cba896ccbaf272640a042"
        }
      ]
    }
  ]
}