{
  "formatVersion": "1.1",
  "component": {
    "url": "../../window-core/9999.0.0-SNAPSHOT/window-core-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.androidx.window",
    "module": "window-core",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "window-core-js-9999.0.0-SNAPSHOT.klib",
          "url": "window-core-js-9999.0.0-SNAPSHOT.klib",
          "size": 19943,
          "sha512": "82fe8cd740802889cb25b28a233f74fd9695c4497d594d85ed54bea2c24f43b568573c2894390c2db7ae6a8f46adc76b5afdccfa172390b63adfc5197f7ff314",
          "sha256": "50115c17e8a6d2c820b507fb0ca7d07c7f01b65dd11229d290db13bb5cfb9ec9",
          "sha1": "2822baab1001bed1362081840bb99a756a01b572",
          "md5": "cbe2cf96689dedbddca235426e0253bc"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "window-core-js-9999.0.0-SNAPSHOT.klib",
          "url": "window-core-js-9999.0.0-SNAPSHOT.klib",
          "size": 19943,
          "sha512": "82fe8cd740802889cb25b28a233f74fd9695c4497d594d85ed54bea2c24f43b568573c2894390c2db7ae6a8f46adc76b5afdccfa172390b63adfc5197f7ff314",
          "sha256": "50115c17e8a6d2c820b507fb0ca7d07c7f01b65dd11229d290db13bb5cfb9ec9",
          "sha1": "2822baab1001bed1362081840bb99a756a01b572",
          "md5": "cbe2cf96689dedbddca235426e0253bc"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "window-core-js-9999.0.0-SNAPSHOT-sources.jar",
          "url": "window-core-js-9999.0.0-SNAPSHOT-sources.jar",
          "size": 8804,
          "sha512": "ae70222feba801a749b9c9498250c034d6ef44bfabc2edbce34503b0492fe6c7a2f2c0c0a62071cffc7b3aaa48dacbebcb44bf12a96375d60a61c7c58ee68ce5",
          "sha256": "7f12a1dfe66bf3f3d0f68395b1f749377e533cdd245dffa3465e07d5acc0536e",
          "sha1": "37942415b980a2d51e646603b246932976db31b8",
          "md5": "07828aa7ba8527c29503ee6042e34503"
        }
      ]
    }
  ]
}