{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation-layout/9999.0.0-SNAPSHOT/foundation-layout-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.foundation",
    "module": "foundation-layout",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "uikitArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-layout-uikitArm64Main-9999.0.0-SNAPSHOT.klib",
          "url": "foundation-layout-uikitarm64-9999.0.0-SNAPSHOT.klib",
          "size": 480738,
          "sha512": "905f3e10628741100ffbfaeb1fd3fd198d0fd0500f6cdac37735845d103425c109c16f40f1989e104e92122cac71cf7ccdf8b44e9cfadd5fd647c103685f9507",
          "sha256": "2fb1764b25f8915514a1871bd3d6891db770ecbbeaab22958d545c1a3dfb92c2",
          "sha1": "7266ddc9ace82430211f306f1aa4b8017658a096",
          "md5": "e722075b51ecdb2e143144a6ee053ea0"
        }
      ]
    },
    {
      "name": "uikitArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "foundation-layout-uikitarm64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "foundation-layout-uikitarm64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 88678,
          "sha512": "91f9479d0159ebb98d649e4901d2cf23d97a5fe4631daa9ba2e1e5b94a9a25d1863a836c27bd94102f5d47ef0d62637e9ece538b949593e0a14d42de976b4c24",
          "sha256": "0a0836bb94b71629650371407e7a8384bf85458481b31c926fb8b8796346fbc2",
          "sha1": "64773f9024c58694dcdbc4414e2ebc06b05927af",
          "md5": "8312ab38c444c721a262f77b82e1b570"
        }
      ]
    },
    {
      "name": "uikitArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-layout-uikitarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "url": "foundation-layout-uikitarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "size": 4536,
          "sha512": "94301d95e3399fdc68f7c634606426cc46a0308e8438a72513a0d73beb12cd7ff779399aed249953250cb5726d54e7d85db0e1214d0bf104fdb71e4430458bb8",
          "sha256": "02e6e5614905a466f3d234c4027ecdbfabd83dfb9acc53c9978cac4789fb3e7e",
          "sha1": "5d2091824cae5b6bb743c287efdd62677043d505",
          "md5": "6ebe493bf451af023275a1d99d0be394"
        }
      ]
    }
  ]
}