{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-test/9999.0.0-SNAPSHOT/ui-test-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-test",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "ui-test-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 419548,
          "sha512": "4dbb141bdd13dc160bac1931451142c22438ce5ad23815e7d8af380b18c09dc15a06335d6fd43c91939d0343cfbcb13d880368530392c3a750cb362db46b0229",
          "sha256": "29703542b2c7bed748ee46b5c41e56e55f383f3b19407233e5f9281a2633f069",
          "sha1": "d4e6a008194cd5eaabc83ada842fd216d1cf6db3",
          "md5": "fbc462df7158f23d12d43d9a60240f18"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "ui-test-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 419548,
          "sha512": "4dbb141bdd13dc160bac1931451142c22438ce5ad23815e7d8af380b18c09dc15a06335d6fd43c91939d0343cfbcb13d880368530392c3a750cb362db46b0229",
          "sha256": "29703542b2c7bed748ee46b5c41e56e55f383f3b19407233e5f9281a2633f069",
          "sha1": "d4e6a008194cd5eaabc83ada842fd216d1cf6db3",
          "md5": "fbc462df7158f23d12d43d9a60240f18"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "ui-test-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "url": "ui-test-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "size": 131325,
          "sha512": "b6fa4403aeaa5ffa47d58df921565c460fb64d4704e3724ca0b0f8ec93db522156f2595a72e5013796dc24aa67aa65ab5ca46d79a06e09bd2944fbdd0514f0f9",
          "sha256": "af8e9bcbfeed068ba3ba5fb59727eda133a82b07a2014c6a2ba5b13925f1c9a2",
          "sha1": "025a0846e2b27f45d503b41b4059733525a51133",
          "md5": "e5bf87da0a30f0e3824d4b23165bc602"
        }
      ]
    }
  ]
}