{
  "formatVersion": "1.1",
  "component": {
    "url": "../../savedstate/9999.0.0-SNAPSHOT/savedstate-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.androidx.savedstate",
    "module": "savedstate",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-js-9999.0.0-SNAPSHOT.klib",
          "url": "savedstate-js-9999.0.0-SNAPSHOT.klib",
          "size": 90379,
          "sha512": "21f712f76428f189dec253ff627a5fc8c785342c9b5476f9702334e1e873ab8f7e8c3bb234e7e48288ebe99643af41e0e8ff0437c2f22d0d3dd69261fcc543ef",
          "sha256": "dab37b35b4d307c5f62f1b4b50256d3c8f56882998ced41a79c3b16639eeacc3",
          "sha1": "52298629f4548ec1d45e74ac2a13433b11297b6d",
          "md5": "07791acc949c0a46ca97893a811f9609"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-js-9999.0.0-SNAPSHOT.klib",
          "url": "savedstate-js-9999.0.0-SNAPSHOT.klib",
          "size": 90379,
          "sha512": "21f712f76428f189dec253ff627a5fc8c785342c9b5476f9702334e1e873ab8f7e8c3bb234e7e48288ebe99643af41e0e8ff0437c2f22d0d3dd69261fcc543ef",
          "sha256": "dab37b35b4d307c5f62f1b4b50256d3c8f56882998ced41a79c3b16639eeacc3",
          "sha1": "52298629f4548ec1d45e74ac2a13433b11297b6d",
          "md5": "07791acc949c0a46ca97893a811f9609"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "savedstate-js-9999.0.0-SNAPSHOT-sources.jar",
          "url": "savedstate-js-9999.0.0-SNAPSHOT-sources.jar",
          "size": 33884,
          "sha512": "6c1e589bc464a16f3f349f1b5c901609938fbeb2ac3eac48d5a77bcb153a4fb5646b98400629a83144cffa5d38d3244befaa69f39680e676eda895ef3a65f8fd",
          "sha256": "611a1152627f0720faeb67f2b99821b784b85f3d41b1519f16f31b38d0193bfa",
          "sha1": "37f697a351ee73961f22b309722544b846d3175e",
          "md5": "660d146cdea41eea85dfe0cd3e41b4a1"
        }
      ]
    }
  ]
}