{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lifecycle-viewmodel/9999.0.0-SNAPSHOT/lifecycle-viewmodel-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.androidx.lifecycle",
    "module": "lifecycle-viewmodel",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-js-9999.0.0-SNAPSHOT.klib",
          "url": "lifecycle-viewmodel-js-9999.0.0-SNAPSHOT.klib",
          "size": 47932,
          "sha512": "0138b2c6ce76e4b1d724b193ec1fdc7e80cc935835a7f19587e127a983c2ef14fc6ec6e4873310dc2cf25ba792c6a2ebaf4ed8e760227c614a46b06793dd0ec6",
          "sha256": "61f13dba39c2e941d8c36d975b2006a913077391b825d88f80d656768e517225",
          "sha1": "15204a437350549140e463033ba4b7f2e1dbaed4",
          "md5": "46e6201a33657e36ceb7844f691de09f"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-js-9999.0.0-SNAPSHOT.klib",
          "url": "lifecycle-viewmodel-js-9999.0.0-SNAPSHOT.klib",
          "size": 47932,
          "sha512": "0138b2c6ce76e4b1d724b193ec1fdc7e80cc935835a7f19587e127a983c2ef14fc6ec6e4873310dc2cf25ba792c6a2ebaf4ed8e760227c614a46b06793dd0ec6",
          "sha256": "61f13dba39c2e941d8c36d975b2006a913077391b825d88f80d656768e517225",
          "sha1": "15204a437350549140e463033ba4b7f2e1dbaed4",
          "md5": "46e6201a33657e36ceb7844f691de09f"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-js-9999.0.0-SNAPSHOT-sources.jar",
          "url": "lifecycle-viewmodel-js-9999.0.0-SNAPSHOT-sources.jar",
          "size": 30137,
          "sha512": "34906404f925bfadca6dcab47321b18a35ea8a1a9920077358cdc44afe5c3a43eb1a25b21a7c44b1dc1ec8e2aaf3dd567d8ece73287daee5745627c2ae787c87",
          "sha256": "cd1290e4a63a3ed609f0874da67e0f00aec86d8cc6e64e2efebee149c00e08f8",
          "sha1": "51d235c31bfaad90835f2ca4b1a322958df38c5d",
          "md5": "fb93bf6b4cb32067378d9b393f4db39e"
        }
      ]
    }
  ]
}