{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-ripple/9999.0.0-SNAPSHOT/material-ripple-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.material",
    "module": "material-ripple",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-desktop-9999.0.0-SNAPSHOT.jar",
          "url": "material-ripple-desktop-9999.0.0-SNAPSHOT.jar",
          "size": 74699,
          "sha512": "93526015f16ae5a30285f1f1610ad2fad93c109f69203ff946e2eef35ae777c2ac85cfe4fe0735c35b9c894ef39e2e18579e3993207d89a494b8ec15d1009693",
          "sha256": "bd6f897bec390902e255dd3e1d72d76398d5e82debd4f0c06c30a5b5f0ac4955",
          "sha1": "828e54d21ce13053dd7b705f66bfb332bb38204b",
          "md5": "8e9f0f8704d560e6b53c38ea0e858443"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-desktop-9999.0.0-SNAPSHOT.jar",
          "url": "material-ripple-desktop-9999.0.0-SNAPSHOT.jar",
          "size": 74699,
          "sha512": "93526015f16ae5a30285f1f1610ad2fad93c109f69203ff946e2eef35ae777c2ac85cfe4fe0735c35b9c894ef39e2e18579e3993207d89a494b8ec15d1009693",
          "sha256": "bd6f897bec390902e255dd3e1d72d76398d5e82debd4f0c06c30a5b5f0ac4955",
          "sha1": "828e54d21ce13053dd7b705f66bfb332bb38204b",
          "md5": "8e9f0f8704d560e6b53c38ea0e858443"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "material-ripple-desktop-9999.0.0-SNAPSHOT-sources.jar",
          "url": "material-ripple-desktop-9999.0.0-SNAPSHOT-sources.jar",
          "size": 15155,
          "sha512": "25bfb0749142341f01286e8d73b3c7f13484c99a4371f71c1dbbc1255d93965c9f0ce79dba7a9d2b2ec3df3ee74282e5017da2dde5e8528caa5c393d1622faa2",
          "sha256": "0a7c4f2293831fcfe52f3f294000cb338f9d8ec18499ca3e6adf3c5f3d391180",
          "sha1": "72e0376dbad6b3fbb014c5368599840f23399c05",
          "md5": "5af7b1c99bd53c2c30d0ed1aca8d872f"
        }
      ]
    }
  ]
}