{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material3/9999.0.0-SNAPSHOT/material3-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.material3",
    "module": "material3",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "uikitX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.11"
          },
          "excludes": [
            {
              "group": "org.jetbrains.compose.ui",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "material3-uikitX64Main-9999.0.0-SNAPSHOT.klib",
          "url": "material3-uikitx64-9999.0.0-SNAPSHOT.klib",
          "size": 3234637,
          "sha512": "304aed2ea78591f0661a061ad5f936235529a4c0963fa94ce4ccd0437de4ce8c52a78844fffe5f344585143109922321db9c27beda9fc8975613b588c82cf77c",
          "sha256": "8165ed1919e6f64eaff303311062c6177d526692af4173276af565d89f73f55a",
          "sha1": "18fe4603012ce9204665391faecae430d101baea",
          "md5": "1ea23f86dd852e8262eae0ab82f36267"
        }
      ]
    },
    {
      "name": "uikitX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "material3-uikitx64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "material3-uikitx64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 653323,
          "sha512": "06d503c39bbc861ce7e742f899d7b005dcc3b8fcb314a5c68afe5e4e49fbcbfc13aa24067baded92bdb48e9f2145490d1dc75a08a2202645976ecc326643d9ee",
          "sha256": "afea09614e21caa187a486d0eda9db3533ec5e92b077a2fc1b0823009813f3b2",
          "sha1": "803cc46e919535fb79e0195ec9a7343b86fe97e8",
          "md5": "b6f27fa96e3f7139b088b84608046ba6"
        }
      ]
    },
    {
      "name": "uikitX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.11"
          },
          "excludes": [
            {
              "group": "org.jetbrains.compose.ui",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "material3-uikitx64-9999.0.0-SNAPSHOT-metadata.jar",
          "url": "material3-uikitx64-9999.0.0-SNAPSHOT-metadata.jar",
          "size": 9291,
          "sha512": "b9fb1955c6a02a1d491b4006cd9719ae34c5ec31d509b7988f540b3e48613ecd0eac00f174c892e936b7a0bb8852a7ba02da4b3ac64ddda5426c84d4469a38ec",
          "sha256": "44cafe50b627ac8103116e91e4e45e0fea1ec926d18e7295cc0b66eed2170ac0",
          "sha1": "1bb5f150323f2565104ad2e8c691658e0796f648",
          "md5": "9cd8fc88d9abbacc17271abe0f8229c6"
        }
      ]
    }
  ]
}