{
  "formatVersion": "1.1",
  "component": {
    "url": "../../navigation-runtime/9999.0.0-SNAPSHOT/navigation-runtime-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.androidx.navigation",
    "module": "navigation-runtime",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-linuxArm64Main-9999.0.0-SNAPSHOT.klib",
          "url": "navigation-runtime-linuxarm64-9999.0.0-SNAPSHOT.klib",
          "size": 109572,
          "sha512": "bb512c8b93e00fe317c64e671882837919a35a3f151d85a977e8357953fdaa7b3ced735e8d758449ae677a8ce4610acc0337c33f6709a88cab0741696c5f4edc",
          "sha256": "02bba8b6e614b43d6103295bf5c003709f1c3d0d8ab9da474d6a3b7573cd1668",
          "sha1": "13c11563a08141af50ade21254dda0185aa3930d",
          "md5": "664343ad2887b2b3694fda2ced767279"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "navigation-runtime-linuxarm64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "navigation-runtime-linuxarm64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 34783,
          "sha512": "bebb7fc51ffccf8af2490694598c189cfc4bc0b853db413994a91198a7fa9433851caa53970af50d90307c77d10a4a98307ecb21025e40d2bf9dad7e047c57f2",
          "sha256": "2da784bf41be149555d392b076b5e69a129f1660876bcd2edb8f9603254df2b5",
          "sha1": "f64171d64c66ca5718afd79a5e2c449ba6550d77",
          "md5": "55110d9acb543e8e057565082306ad02"
        }
      ]
    }
  ]
}