{
  "formatVersion": "1.1",
  "component": {
    "url": "../../collection/9999.0.0-SNAPSHOT/collection-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.collection-internal",
    "module": "collection",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0-beta02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "collection-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "collection-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 2644,
          "sha512": "fa4a5361dbe7c1ea9efee4cfedc0a775d56bde44007481ced00fc0d7e518b1febe609685d27b9e3bdc1d55756526f9ea542c3bd51ebd2d9dd68572f506f05772",
          "sha256": "73f913c51f3f0b004138b98c164f956938c739c1895c46f5046498982cd317b7",
          "sha1": "6f68fca67f3c26aff2f345b72921ed3f4382d097",
          "md5": "b1b27ee97963dd693e25757a7118a6c1"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0-beta02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "collection-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "collection-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 2644,
          "sha512": "fa4a5361dbe7c1ea9efee4cfedc0a775d56bde44007481ced00fc0d7e518b1febe609685d27b9e3bdc1d55756526f9ea542c3bd51ebd2d9dd68572f506f05772",
          "sha256": "73f913c51f3f0b004138b98c164f956938c739c1895c46f5046498982cd317b7",
          "sha1": "6f68fca67f3c26aff2f345b72921ed3f4382d097",
          "md5": "b1b27ee97963dd693e25757a7118a6c1"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "collection-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "url": "collection-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "size": 1171,
          "sha512": "f6200d6e0580d15451a168a5d9ab1bb80156255cae938d5c0f4ce8a3801ffc7e3f808789c60628f5dc86c729461444e7abc2c8216563b2398c21b32bd0a05630",
          "sha256": "c2b0ebd60ccb311adc4649d7053ea0ab7d695a33260be1ac4165ff80d9e903e0",
          "sha1": "50095a3e0735cce54c69528d58031607900c51d6",
          "md5": "55ac8ea0d217afee0764372661886e0e"
        }
      ]
    }
  ]
}