{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-navigation/9999.0.0-SNAPSHOT/material-navigation-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.material",
    "module": "material-navigation",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "material-navigation-desktop-9999.0.0-SNAPSHOT.jar",
          "url": "material-navigation-desktop-9999.0.0-SNAPSHOT.jar",
          "size": 53478,
          "sha512": "0603790cfe12029622f25c22c28cc0d1d765d9e411afbe722e507a5fc6985835b26f57ed1832983a6025a154975c31ffbf82e78086c6eaadd9e52c12840a6d4b",
          "sha256": "57a65f2e79efbf5c679716d3d4343a4fbe252092e5a1c484b3e5733ccce60280",
          "sha1": "50ed640dab303f979c004a5d6768c8e1f725675b",
          "md5": "af6e387154d7998fe49f7d362e582a25"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "material-navigation-desktop-9999.0.0-SNAPSHOT.jar",
          "url": "material-navigation-desktop-9999.0.0-SNAPSHOT.jar",
          "size": 53478,
          "sha512": "0603790cfe12029622f25c22c28cc0d1d765d9e411afbe722e507a5fc6985835b26f57ed1832983a6025a154975c31ffbf82e78086c6eaadd9e52c12840a6d4b",
          "sha256": "57a65f2e79efbf5c679716d3d4343a4fbe252092e5a1c484b3e5733ccce60280",
          "sha1": "50ed640dab303f979c004a5d6768c8e1f725675b",
          "md5": "af6e387154d7998fe49f7d362e582a25"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "material-navigation-desktop-9999.0.0-SNAPSHOT-sources.jar",
          "url": "material-navigation-desktop-9999.0.0-SNAPSHOT-sources.jar",
          "size": 11570,
          "sha512": "397c1283b60ee70cc0326f711f726846f08495ae5793358a0f6bfe4747cbd78d81025e247e4018912858e4782e10445ed81186f7da6068c83f17fb091023b303",
          "sha256": "d9bea1972c3ec3db40a1bc2e410f1696ce9a42db21675fa9b07a606bae2bf933",
          "sha1": "cc6aec6958b041ee1508926435024ed0626759b6",
          "md5": "d8cef57940affed31e74476e20d72aa6"
        }
      ]
    }
  ]
}