{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-uikit/9999.0.0-SNAPSHOT/ui-uikit-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-uikit",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "uikitX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-uikit-uikitX64Main-9999.0.0-SNAPSHOT.klib",
          "url": "ui-uikit-uikitx64-9999.0.0-SNAPSHOT.klib",
          "size": 34434,
          "sha512": "ef30589178bcfe9cf291513dbe4e9b6cb173f7c14f22e4fa9ea8d229712732ce5996a1301a2511b3a31935fa62fad304460d99690fec94f6d016432c1312d48f",
          "sha256": "68b40535e9b9e2f6a9a512412c134820cafb3595cbb529f08530c506cdd0b840",
          "sha1": "a34024ba1ebfda7c3cf66fec72c90fd60131a1a1",
          "md5": "6d42d4a146563a050b81e2ed39111689"
        },
        {
          "name": "ui-uikit-uikitX64Cinterop-utilsMain-9999.0.0-SNAPSHOT.klib",
          "url": "ui-uikit-uikitx64-9999.0.0-SNAPSHOT-cinterop-utils.klib",
          "size": 16855,
          "sha512": "1c724ee40df6225ccef7f9f00e8456e036a5f9395c23af53c8a82ae1a933b65b011d58239d4aceefe23b5a27bbe66caf85f0e139bf2974bdc6d5223160ce80a2",
          "sha256": "dc63521c85eb51e245eb69053a46e12711451ea4764d522707648c143d739813",
          "sha1": "17604adb2e138219b77de475d487e5ce6771e0c3",
          "md5": "a3e3b544b200baf931518b32b132412c"
        }
      ]
    },
    {
      "name": "uikitX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-uikit-uikitx64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "ui-uikit-uikitx64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 1490,
          "sha512": "d6dc3e7f01c622f0ea48c15b68dd3bd723a920b41f0b1cc815a262f8c90d27005f8dce99adc3b3ccf4812250ef7e74cf35479950fdf71a195a45d93ba5acbdb3",
          "sha256": "b786874f6ed58f0ba4b5a0c2e47b7361c73b1aaab5f7eb1d608a026944a86265",
          "sha1": "aba8ee840667a30a5ec3805304797479188efcc4",
          "md5": "740df642ae42cb3d618bbb1f1d5693f3"
        }
      ]
    },
    {
      "name": "uikitX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-uikit-uikitx64-9999.0.0-SNAPSHOT-metadata.jar",
          "url": "ui-uikit-uikitx64-9999.0.0-SNAPSHOT-metadata.jar",
          "size": 30084,
          "sha512": "21a0a1b61147020a6a2b93e839142a2f62cd48cbb0339d5cc4fb2f155e6503277b72e1d025f2edf0103edb4bc582f6f9463d2967a81d11d16686718919be6391",
          "sha256": "c803ce0ce443b7ef840d1c0fee0fa28a7020300d9db9e7dba443ae9f8183e0cb",
          "sha1": "74af7b7c6dd240ee6877d261427339776df860dc",
          "md5": "f9175b3a92357a5a0d819ea8881ccc24"
        }
      ]
    }
  ]
}