{
  "formatVersion": "1.1",
  "component": {
    "url": "../../adaptive/9999.0.0-SNAPSHOT/adaptive-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.material3.adaptive",
    "module": "adaptive",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "adaptive-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "adaptive-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 19357,
          "sha512": "61d5f637dc1d74d7588def0db289a68460919a40d09be29d024facc55f68c0db87054f46fb352be6e160a4b330a1172c4c7436a6958556df945c143eb312510c",
          "sha256": "9ca4c9f72e6d090608f4d94f1054f55d13d99087f943513da7e0b577678a5027",
          "sha1": "308149edf985944ae998c17e50001b0e80aaf0dd",
          "md5": "077b5bfbba6797e34be9a245c432661c"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "adaptive-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "adaptive-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 19357,
          "sha512": "61d5f637dc1d74d7588def0db289a68460919a40d09be29d024facc55f68c0db87054f46fb352be6e160a4b330a1172c4c7436a6958556df945c143eb312510c",
          "sha256": "9ca4c9f72e6d090608f4d94f1054f55d13d99087f943513da7e0b577678a5027",
          "sha1": "308149edf985944ae998c17e50001b0e80aaf0dd",
          "md5": "077b5bfbba6797e34be9a245c432661c"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "adaptive-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "url": "adaptive-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "size": 7579,
          "sha512": "87a9d2b75935aeec2c43db051657f135490063d5bb50ac35e457ee80f3a7dafdc718b4caa11f0aba99e2f67a2dec2b66f2a480b7dbaf5dfa60cc274d39c0b01f",
          "sha256": "c32dcea1cd1cc0b2f5b4bcd3d5d81a11ef123275c2692ba4f687631d53e50860",
          "sha1": "7c47642ef0ff20e4ce0ae6f529217d0a7ffc76af",
          "md5": "a083682ea78e440c9b6d9e2b8eca7788"
        }
      ]
    }
  ]
}