{
  "formatVersion": "1.1",
  "component": {
    "url": "../../animation/9999.0.0-SNAPSHOT/animation-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.animation",
    "module": "animation",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "animation-js-9999.0.0-SNAPSHOT.klib",
          "url": "animation-js-9999.0.0-SNAPSHOT.klib",
          "size": 362680,
          "sha512": "82d66afaada590fb761d60c87ee31943763ee35510a28b028bf06cd4b74d7fd34460f52ddb9bfc80639a2d138bb449a182367fed0641a93a8bd9ff3b4599eda8",
          "sha256": "98916ed148a060eeb061d2bd45164787fe2dc425ab9ce688a0ddfda7ff44f3d6",
          "sha1": "cdb8112cdca647d1926b32cdde81cfa86330c5db",
          "md5": "70ea595526d66f7f741dde9d9570c657"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "animation-js-9999.0.0-SNAPSHOT.klib",
          "url": "animation-js-9999.0.0-SNAPSHOT.klib",
          "size": 362680,
          "sha512": "82d66afaada590fb761d60c87ee31943763ee35510a28b028bf06cd4b74d7fd34460f52ddb9bfc80639a2d138bb449a182367fed0641a93a8bd9ff3b4599eda8",
          "sha256": "98916ed148a060eeb061d2bd45164787fe2dc425ab9ce688a0ddfda7ff44f3d6",
          "sha1": "cdb8112cdca647d1926b32cdde81cfa86330c5db",
          "md5": "70ea595526d66f7f741dde9d9570c657"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "animation-js-9999.0.0-SNAPSHOT-sources.jar",
          "url": "animation-js-9999.0.0-SNAPSHOT-sources.jar",
          "size": 77217,
          "sha512": "f9cf27d062f98c32e84555a0b818e9fa347a33f13480f9d7fd0c8f61281229e89ae132c0be20b96b42aed1c05bebb70845e869aee95ab551660f909fdbbae2b8",
          "sha256": "4e240ffe300f856770b4ec9895e9266fa2a4519f69a7aebe48ada5e398818aac",
          "sha1": "885a1a43df6802ede4a07dfb7a8aa01796c73fd2",
          "md5": "cfe540989efae83f1c1561349dc30bb6"
        }
      ]
    }
  ]
}