{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lifecycle-common/9999.0.0-SNAPSHOT/lifecycle-common-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.androidx.lifecycle",
    "module": "lifecycle-common",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-common-watchosArm32Main-9999.0.0-SNAPSHOT.klib",
          "url": "lifecycle-common-watchosarm32-9999.0.0-SNAPSHOT.klib",
          "size": 22840,
          "sha512": "27df32ab1eccaa4c5c8ffaa33278e57be018ffcc82bea7fc31cc14e3ac53d59a365500418490c1e8c01ec94e151b2c0872cd9d129b30a17b4b37a1aa40fbccbd",
          "sha256": "dbe4acb8d583329ec3237705d19a34f093bd2cb5b895a76dd82a3a6b251b4c4d",
          "sha1": "97ffef08a666dfe49d5767d8a46dc0d8e28d8398",
          "md5": "145f6feaf206a88bfcb44686b29e9155"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "lifecycle-common-watchosarm32-9999.0.0-SNAPSHOT-sources.jar",
          "url": "lifecycle-common-watchosarm32-9999.0.0-SNAPSHOT-sources.jar",
          "size": 11665,
          "sha512": "3864839220d94775f4d86aff51de908a38ca7fb236e2ed4e307d5826c4dc953ce52152c624b00b792a509d7191665dd71263bf93226a2274db7b00e5c3e3de5c",
          "sha256": "6727ef61af9b1f6ef365576aac7699b86c3b3ec226b2a32c972c825cc05472f8",
          "sha1": "825d6fa5060790cb1a7bfdd4bbdb9b05c5a7087f",
          "md5": "24363d391ae4e5ecf6dd3fd6faf000e1"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-common-watchosarm32-9999.0.0-SNAPSHOT-metadata.jar",
          "url": "lifecycle-common-watchosarm32-9999.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}