{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lifecycle-viewmodel/9999.0.0-SNAPSHOT/lifecycle-viewmodel-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.androidx.lifecycle",
    "module": "lifecycle-viewmodel",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-tvosSimulatorArm64Main-9999.0.0-SNAPSHOT.klib",
          "url": "lifecycle-viewmodel-tvossimulatorarm64-9999.0.0-SNAPSHOT.klib",
          "size": 51710,
          "sha512": "02df7af9745a8911b47aaf2176f6998c9cc4167c3ac2171543039372e31a0f02e04cea1b86fc677082fd7f5a665677f6daf87e801593bb85c9b46d56f473fd2e",
          "sha256": "34c43e38a04d4e8b1295cebaf97d0be28a4e34a04e493e820a6949572278e199",
          "sha1": "45c7bb71315452eaaffbbd8a7aad5d65cf1c9fc3",
          "md5": "8f3eaea0e17d7fdc81f8629c6e55e6d6"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-tvossimulatorarm64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "lifecycle-viewmodel-tvossimulatorarm64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 32147,
          "sha512": "b3d87fc8c884a8550024c1d1c20137260633a512c6c170d5940fe694c6558921b5e7d2579c8aa02ceb9fde688f69c57cfb9338380845fe5b70bd84403a6997e3",
          "sha256": "d5d1d3427ccdc62c395fccfa49999b671e1d9c233e90d130837b8a11e2eadff7",
          "sha1": "88d32d3ad3d25c390a0af831cd806ba74094e599",
          "md5": "3c97b027476099ca2ed146d380168e71"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-tvossimulatorarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "url": "lifecycle-viewmodel-tvossimulatorarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "size": 4381,
          "sha512": "fcbfd0fc64c70c14c409d322a0415cf3097eff5796cae5e0dfd9f86c4400fb49443980baaf05efbb21264f1a93fab8633d4567f2b6ff6281605fa7fc497662b3",
          "sha256": "351e74a9a2c8fee15931ba3b092219d3c9e3e98fbf3e2e70e20c5e845ee0fa30",
          "sha1": "3e21f4e5b2b5b01af581f24d566225a52007850f",
          "md5": "355b5c1f016214843735f06617b23713"
        }
      ]
    }
  ]
}