{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material3-window-size-class/9999.0.0-SNAPSHOT/material3-window-size-class-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.material3",
    "module": "material3-window-size-class",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-desktop-9999.0.0-SNAPSHOT.jar",
          "url": "material3-window-size-class-desktop-9999.0.0-SNAPSHOT.jar",
          "size": 18208,
          "sha512": "598c451f410d43f1fe26eccf81ef7dc2b42fdcd5655bf50a15c2803aabcf44b4afed3dee228fa49c5b83d6c9725c0f30100bf1615aef9317b6851ed317152313",
          "sha256": "e0e1298b7301bacc4fc64f225ef7665193a2ec9001f1b9a649039ef5bd3a7d19",
          "sha1": "f93d71049128dfe8284e905eef2317a0ecabf467",
          "md5": "a11678f30fe2d6549075c9ba326a035a"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-desktop-9999.0.0-SNAPSHOT.jar",
          "url": "material3-window-size-class-desktop-9999.0.0-SNAPSHOT.jar",
          "size": 18208,
          "sha512": "598c451f410d43f1fe26eccf81ef7dc2b42fdcd5655bf50a15c2803aabcf44b4afed3dee228fa49c5b83d6c9725c0f30100bf1615aef9317b6851ed317152313",
          "sha256": "e0e1298b7301bacc4fc64f225ef7665193a2ec9001f1b9a649039ef5bd3a7d19",
          "sha1": "f93d71049128dfe8284e905eef2317a0ecabf467",
          "md5": "a11678f30fe2d6549075c9ba326a035a"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "material3-window-size-class-desktop-9999.0.0-SNAPSHOT-sources.jar",
          "url": "material3-window-size-class-desktop-9999.0.0-SNAPSHOT-sources.jar",
          "size": 8197,
          "sha512": "2b8615e56ff0ec6875d36555d44879b3e1f2291574f406cfe9ef6864f3e26e59bbd5a13af786144eb69d4984a0105bf0d7b1b5dcd40e0e3cdc84dee499b79db5",
          "sha256": "84d3f8d3ac730ddefb63f58e9e824a13f4901a63727a10fcb64032e4dd6c7aa4",
          "sha1": "512e298d73924994b8e3b9e095a3c7e690b9c810",
          "md5": "77dbe2be9bc6466b63c5f8d64dae6dbe"
        }
      ]
    }
  ]
}