{
  "formatVersion": "1.1",
  "component": {
    "url": "../../navigation-runtime/9999.0.0-SNAPSHOT/navigation-runtime-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.androidx.navigation",
    "module": "navigation-runtime",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-desktop-9999.0.0-SNAPSHOT.jar",
          "url": "navigation-runtime-desktop-9999.0.0-SNAPSHOT.jar",
          "size": 84589,
          "sha512": "c3e526682ff1baabc7489fd20cbdfea41e5e9754eb11fb0982c965c7984a59577d3a8db3dbe1ae3b9fac690a9fac25073c2cee53fcaf72a0a5623c89485b1d12",
          "sha256": "95f37b8acb76d3c96a6bc97c3db0bb6a65ea16c6eb519e39350cc99e1df463c1",
          "sha1": "ef3deb61bf0b1f6a5185423fd3a865cd3c6d9aff",
          "md5": "993f5b1293ffc99d8c4080c4e85eaa61"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-desktop-9999.0.0-SNAPSHOT.jar",
          "url": "navigation-runtime-desktop-9999.0.0-SNAPSHOT.jar",
          "size": 84589,
          "sha512": "c3e526682ff1baabc7489fd20cbdfea41e5e9754eb11fb0982c965c7984a59577d3a8db3dbe1ae3b9fac690a9fac25073c2cee53fcaf72a0a5623c89485b1d12",
          "sha256": "95f37b8acb76d3c96a6bc97c3db0bb6a65ea16c6eb519e39350cc99e1df463c1",
          "sha1": "ef3deb61bf0b1f6a5185423fd3a865cd3c6d9aff",
          "md5": "993f5b1293ffc99d8c4080c4e85eaa61"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "navigation-runtime-desktop-9999.0.0-SNAPSHOT-sources.jar",
          "url": "navigation-runtime-desktop-9999.0.0-SNAPSHOT-sources.jar",
          "size": 34695,
          "sha512": "84931e2edfa9bbba94dad3492f1cdc9e22d07ab6a020f9cf6e74799f59ac0c04d9af6794f815a9d2b53d1716bc370db80069a39344e6b4a09928453fef4b8509",
          "sha256": "dbff2c7143e7e12077f6331b45fc367f3feee14bac5ee60dbb8d5838a4af16f6",
          "sha1": "30c0ebb6134af162fefc170fb7d3e35a83faeb16",
          "md5": "dd6b38fab79f2171f29b0f04b0357c86"
        }
      ]
    }
  ]
}