{
  "formatVersion": "1.1",
  "component": {
    "url": "../../savedstate/9999.0.0-SNAPSHOT/savedstate-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.androidx.savedstate",
    "module": "savedstate",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-desktop-9999.0.0-SNAPSHOT.jar",
          "url": "savedstate-desktop-9999.0.0-SNAPSHOT.jar",
          "size": 76551,
          "sha512": "d4201eaaf19026f815dcb6b7c46c96649836696b19895cedaf009702c853f375642cdae762a9d1afa76fd3b2088c98a18309f6b441f9e6243f22147ce5a28318",
          "sha256": "e35f7ceda6bb6bbde1c9c0e18ccd7aa6ce1b75e34609f807ea2848060ad8e1b7",
          "sha1": "5828d9127411a0abd1317b582daf64aa31a3683c",
          "md5": "7cd5e1cb017c87e1cf2b8a4ff4679bcb"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-desktop-9999.0.0-SNAPSHOT.jar",
          "url": "savedstate-desktop-9999.0.0-SNAPSHOT.jar",
          "size": 76551,
          "sha512": "d4201eaaf19026f815dcb6b7c46c96649836696b19895cedaf009702c853f375642cdae762a9d1afa76fd3b2088c98a18309f6b441f9e6243f22147ce5a28318",
          "sha256": "e35f7ceda6bb6bbde1c9c0e18ccd7aa6ce1b75e34609f807ea2848060ad8e1b7",
          "sha1": "5828d9127411a0abd1317b582daf64aa31a3683c",
          "md5": "7cd5e1cb017c87e1cf2b8a4ff4679bcb"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "savedstate-desktop-9999.0.0-SNAPSHOT-sources.jar",
          "url": "savedstate-desktop-9999.0.0-SNAPSHOT-sources.jar",
          "size": 33892,
          "sha512": "a8c3bb3b08999764fe5e036bd79c9fe1f034b0f0bdb3bc11ba2de74944174d2eb3c9dfada120f85e1e29278a187f88f4decd8437dcd366703bb0facd361f6a0d",
          "sha256": "2e8919c533a3e3deed9310dd2174590f39e82e17c8817156c824daff92bd7e18",
          "sha1": "fde3c223473035b96070a04e9aadd12366e1884d",
          "md5": "69b40e92d51635cc0f756013613650b3"
        }
      ]
    }
  ]
}