{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.desktop",
    "module": "desktop",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "desktop-metadata-9999.0.0-SNAPSHOT.jar",
          "url": "desktop-9999.0.0-SNAPSHOT.jar",
          "size": 714,
          "sha512": "cc94b78399d25846c2f4888aecbb07f2c8ce4b9a7695fd0422c430204af868bed29d72dba5fc4c4f7cec5a48b9b2816314bdf70f9f1cd0b0682db7432f49be1b",
          "sha256": "bff3d1e895fd5abd54ee725dab59214acabf900e1a0784544d20cf20521bf9f3",
          "sha1": "4c32ea04d4bc9da37919518ff8fe2a1276a61e3c",
          "md5": "ce24486a4f3bd1f1a9e5df1b7687c021"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "desktop-kotlin-9999.0.0-SNAPSHOT-sources.jar",
          "url": "desktop-9999.0.0-SNAPSHOT-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../desktop-jvm/9999.0.0-SNAPSHOT/desktop-jvm-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.desktop",
        "module": "desktop-jvm",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../desktop-jvm/9999.0.0-SNAPSHOT/desktop-jvm-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.desktop",
        "module": "desktop-jvm",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../desktop-jvm/9999.0.0-SNAPSHOT/desktop-jvm-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.compose.desktop",
        "module": "desktop-jvm",
        "version": "9999.0.0-SNAPSHOT"
      }
    }
  ]
}