{
  "formatVersion": "1.1",
  "component": {
    "url": "../../annotation/9999.0.0-SNAPSHOT/annotation-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.annotation-internal",
    "module": "annotation",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "annotation-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 2635,
          "sha512": "ce2d6c256d144e9111b6c704bb3ad136e5ad1e0ec968ffbc3bc3b8172f16b912fd2bb4570f2df395496b2c9f048f4bad88e79b23cf32e2aba21a7d799aac6a82",
          "sha256": "bcf24921ef0d0d9452b95db0e36ea901a775c3b542eaf5b2c2673688ff13d179",
          "sha1": "928cf6e972223095de3f1dcf1efff9d2ec84deca",
          "md5": "19895c2ecff7e61b085252a7b946a498"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "annotation-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 2635,
          "sha512": "ce2d6c256d144e9111b6c704bb3ad136e5ad1e0ec968ffbc3bc3b8172f16b912fd2bb4570f2df395496b2c9f048f4bad88e79b23cf32e2aba21a7d799aac6a82",
          "sha256": "bcf24921ef0d0d9452b95db0e36ea901a775c3b542eaf5b2c2673688ff13d179",
          "sha1": "928cf6e972223095de3f1dcf1efff9d2ec84deca",
          "md5": "19895c2ecff7e61b085252a7b946a498"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "annotation-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "url": "annotation-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "size": 1171,
          "sha512": "f6200d6e0580d15451a168a5d9ab1bb80156255cae938d5c0f4ce8a3801ffc7e3f808789c60628f5dc86c729461444e7abc2c8216563b2398c21b32bd0a05630",
          "sha256": "c2b0ebd60ccb311adc4649d7053ea0ab7d695a33260be1ac4165ff80d9e903e0",
          "sha1": "50095a3e0735cce54c69528d58031607900c51d6",
          "md5": "55ac8ea0d217afee0764372661886e0e"
        }
      ]
    }
  ]
}