{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lifecycle-runtime-compose/9999.0.0-SNAPSHOT/lifecycle-runtime-compose-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.androidx.lifecycle",
    "module": "lifecycle-runtime-compose",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose-macosArm64Main-9999.0.0-SNAPSHOT.klib",
          "url": "lifecycle-runtime-compose-macosarm64-9999.0.0-SNAPSHOT.klib",
          "size": 43308,
          "sha512": "f8d14f6dad17dc69b179ab0a5a7f1240ad610abfdae11a794716a099869c47a0ec58ef0005bd08192b8475a235cfe62ba0ea97378e05d9b6259cd6e0f499c499",
          "sha256": "77a571fd26c0212dc170f3f1b6fdb1219c3f27b39cdf1765658f5ffc5aa98f5e",
          "sha1": "e566ad032f4e198708cf774a8832ae8ae71f8adc",
          "md5": "7e5e82ea426b895c4b8b878a59d96d5d"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "lifecycle-runtime-compose-macosarm64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "lifecycle-runtime-compose-macosarm64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 10368,
          "sha512": "e1f6646c0262ad83f8196dcad09b97d1da215457fb53518097b34c0d9a606f885ef261b2483eb52c8ad9cc5ab8e2254fac4b3880010266b983c86a8a3510177d",
          "sha256": "ab9a6a2fb0f1b26072828db764e896b66bcd98feb21ace6cc4939c0bbf4a82e8",
          "sha1": "4be835c6a3c8d641203febced033ffdd51b9a856",
          "md5": "444a0e79a7cf9bb918ac1317a184595f"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose-macosarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "url": "lifecycle-runtime-compose-macosarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}