{
  "formatVersion": "1.1",
  "component": {
    "url": "../../navigation-common/9999.0.0-SNAPSHOT/navigation-common-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.androidx.navigation",
    "module": "navigation-common",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-desktop-9999.0.0-SNAPSHOT.jar",
          "url": "navigation-common-desktop-9999.0.0-SNAPSHOT.jar",
          "size": 326780,
          "sha512": "2d6e11ad51495e8c0502ef7c1d227d4041974b5dd039d1079b9e3d9c207c2a54697119d4392846d9adf361192880a0f6c30f0e90b7d5fb186ffa03df44535539",
          "sha256": "950be74159c4ac28f372e1a835d9f8dcd6bbfcfc214435d9657618927bdb296c",
          "sha1": "5e77e8a2f6d3afdf6f208aeaa5fa2625cff4a23e",
          "md5": "8f9e09c05c51d0549b855bfbda717355"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-desktop-9999.0.0-SNAPSHOT.jar",
          "url": "navigation-common-desktop-9999.0.0-SNAPSHOT.jar",
          "size": 326780,
          "sha512": "2d6e11ad51495e8c0502ef7c1d227d4041974b5dd039d1079b9e3d9c207c2a54697119d4392846d9adf361192880a0f6c30f0e90b7d5fb186ffa03df44535539",
          "sha256": "950be74159c4ac28f372e1a835d9f8dcd6bbfcfc214435d9657618927bdb296c",
          "sha1": "5e77e8a2f6d3afdf6f208aeaa5fa2625cff4a23e",
          "md5": "8f9e09c05c51d0549b855bfbda717355"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "navigation-common-desktop-9999.0.0-SNAPSHOT-sources.jar",
          "url": "navigation-common-desktop-9999.0.0-SNAPSHOT-sources.jar",
          "size": 100270,
          "sha512": "a94a1bc7fe96679216402309a396fc725b749b23b113d759c4eb543c2eeb7674e8030a69b755e93e19ad0c8f59384c4d1c33fc8c981a21d0931f1a03a014665f",
          "sha256": "782f27ae2b24bc4cf11c24ecccc29bd9b2afb230e28e0357ac5f1ce02767fc34",
          "sha1": "360dfa1c074abeba018576feb8a3523b83499588",
          "md5": "f2c0635488c3c0a58535dddc11e63b5c"
        }
      ]
    }
  ]
}