{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-backhandler/9999.0.0-SNAPSHOT/ui-backhandler-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-backhandler",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "ui-backhandler-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "ui-backhandler-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 25778,
          "sha512": "66e09735e4ff1a23f89e26f85f5d96c38e300e5d684dd15ea56911347f2b6c4a04920d555857199bb7761f96346d09796c68bf44e9dc182e27530d1d8695b04e",
          "sha256": "9b8ee0106cd2bb7c2dd1c0d3f0e27957e525d4f743daca01750d24876f57ae12",
          "sha1": "ff27b9b529cb8cca023e3cc46561e832981fabf0",
          "md5": "602d60e68dc0b5f3ecb2cea20f32655d"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-backhandler-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "ui-backhandler-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 25778,
          "sha512": "66e09735e4ff1a23f89e26f85f5d96c38e300e5d684dd15ea56911347f2b6c4a04920d555857199bb7761f96346d09796c68bf44e9dc182e27530d1d8695b04e",
          "sha256": "9b8ee0106cd2bb7c2dd1c0d3f0e27957e525d4f743daca01750d24876f57ae12",
          "sha1": "ff27b9b529cb8cca023e3cc46561e832981fabf0",
          "md5": "602d60e68dc0b5f3ecb2cea20f32655d"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "ui-backhandler-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "url": "ui-backhandler-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "size": 7636,
          "sha512": "e9b362ffc34e9fbb79be2a16557f231a6f793f8ae7875dbef5bb067cfd1c840aa80e49275d0c51be99c9bdf139127842aac56f60392c993269b5b318752b68d5",
          "sha256": "fadddec18665bd2393cf845b68c412b648f4be78f31de9a73498df66d33a05ea",
          "sha1": "0fed5182ff6d7c70534c6d94304b1e9dfef2f4d2",
          "md5": "7a78025452ae5991257a60cf23340338"
        }
      ]
    }
  ]
}