{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material3-adaptive-navigation-suite/9999.0.0-SNAPSHOT/material3-adaptive-navigation-suite-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.material3",
    "module": "material3-adaptive-navigation-suite",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "uikitArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "material3-adaptive-navigation-suite-uikitArm64Main-9999.0.0-SNAPSHOT.klib",
          "url": "material3-adaptive-navigation-suite-uikitarm64-9999.0.0-SNAPSHOT.klib",
          "size": 58641,
          "sha512": "320acadb15d15ad70a7c7c9aa71ec5684b4ee310b7400507a9b62be3e9f01ff73337da6a271084479d92628ae84c1fd6d16f4417ff75e0239dcde4243afc474b",
          "sha256": "da1081dfbf0626391b7d1204b082d2da9f1888c8706cfc92497a8474339101fb",
          "sha1": "395647211a01669fd3ba74111cfa4afe8d28d233",
          "md5": "539ac3ec44b69635278f32c41135c4fb"
        }
      ]
    },
    {
      "name": "uikitArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "material3-adaptive-navigation-suite-uikitarm64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "material3-adaptive-navigation-suite-uikitarm64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 8869,
          "sha512": "20e9ecfeb003d86c76b45b71f1f444769b3484ca52ff05248fa441d0b53c1002646b4168fd508e0348a3fe2eeeeadcc43a569d15ae0a27f7c660b09840f85e96",
          "sha256": "81a8cd3e5e2ac725df6c951803da02e2f88269292208d92073b0e013080e8ab6",
          "sha1": "827b85ce67919df0f7a9d174a79abdc509585fdd",
          "md5": "97782a2538cf90364472bdbdb082ca05"
        }
      ]
    },
    {
      "name": "uikitArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "material3-adaptive-navigation-suite-uikitarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "url": "material3-adaptive-navigation-suite-uikitarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}