{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-text/9999.0.0-SNAPSHOT/ui-text-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-text",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.9.3"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-js-9999.0.0-SNAPSHOT.klib",
          "url": "ui-text-js-9999.0.0-SNAPSHOT.klib",
          "size": 822394,
          "sha512": "8952c94bf3f9e1f1f2b7a47ada627e8dbb54a7b54c02d9beb9fba9cd13b4f5e60418a2a9740ecb30d22303bd08083e5213e8917b851ea975ee55c95917ab66c2",
          "sha256": "e760e7e27346d2328c554db59b70fc07bd0214dabb943b12b90b467012461f08",
          "sha1": "308a9a3eb02347f33cbdc04639f4995f03053d68",
          "md5": "3ef540fbfde12d46686e9b022bc59802"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlinx-atomicfu-runtime",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.9.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-js-9999.0.0-SNAPSHOT.klib",
          "url": "ui-text-js-9999.0.0-SNAPSHOT.klib",
          "size": 822394,
          "sha512": "8952c94bf3f9e1f1f2b7a47ada627e8dbb54a7b54c02d9beb9fba9cd13b4f5e60418a2a9740ecb30d22303bd08083e5213e8917b851ea975ee55c95917ab66c2",
          "sha256": "e760e7e27346d2328c554db59b70fc07bd0214dabb943b12b90b467012461f08",
          "sha1": "308a9a3eb02347f33cbdc04639f4995f03053d68",
          "md5": "3ef540fbfde12d46686e9b022bc59802"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "ui-text-js-9999.0.0-SNAPSHOT-sources.jar",
          "url": "ui-text-js-9999.0.0-SNAPSHOT-sources.jar",
          "size": 238189,
          "sha512": "72b9b7d20c74e5f46fbc1c7b56ab7e6a82693dd885a7130f80629dd663558b3ffa1a34ed4cb7f538ef224edba1ace15c0f4cb4c75a7c13c412814ae90f444aa6",
          "sha256": "ccf5d135a72a9da977eb73b41cbdbe294b4cb04a8dcba1d2f05e055b6d5eb19a",
          "sha1": "0a831677fb30a30c93d8617827d8f0f6845138f7",
          "md5": "05e866e460a8cef5a466b762735e0f86"
        }
      ]
    }
  ]
}