{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation-layout/9999.0.0-SNAPSHOT/foundation-layout-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.foundation",
    "module": "foundation-layout",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-layout-macosArm64Main-9999.0.0-SNAPSHOT.klib",
          "url": "foundation-layout-macosarm64-9999.0.0-SNAPSHOT.klib",
          "size": 477114,
          "sha512": "c5b0b625865f28664a07645216c065c6dd961f0945390095ea5187c0114a9125428ce3e9b4e88e8e94f4e37ff52889b99005277ae589af54768b538d9629a82b",
          "sha256": "fbee062772828dc78b92955e01e57a805651bd834ccf28de872b29023a637541",
          "sha1": "cccd7b34868e2d3c7042e424aa9dc34d269a6e70",
          "md5": "260e0eb708ce47e22bf91492898dbb6f"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "foundation-layout-macosarm64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "foundation-layout-macosarm64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 87762,
          "sha512": "517f396e4182f5aada99557c5f86ed57909c046fa7ebd3392474823e408c4617c9912e0597f128ab1b3c846f4dcc232aa857c8aa2391059e013a2ac30513e5be",
          "sha256": "e59e798cdce6314f5762103e372aea27d0b007fa0304f181206e22f0b1e9a638",
          "sha1": "ec59fea0b62adb04a39ba5def111165ee0b7b9f0",
          "md5": "42ffc865e61fa0798f7b58e173b1c72e"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-layout-macosarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "url": "foundation-layout-macosarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "size": 4534,
          "sha512": "cd1b7bc9b6758bbe5b79fe34cebe453f583cdd7fa0d2f3371d6723eee96180111d8ba487e0676dcdd748626ca51b590ef2849e4fe1e913937997144d8ce4606a",
          "sha256": "a82bb808eca2d929f3d6f8620c8d29275ff6a6306f74b3672dd6de31036bac7e",
          "sha1": "596c82e491e3c8396dbe7f7d3b3f694af07aaf91",
          "md5": "91dfdb81bbeaf87e4b7ea5cf93b68535"
        }
      ]
    }
  ]
}