{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-uikit/9999.0.0-SNAPSHOT/ui-uikit-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-uikit",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "uikitArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-uikit-uikitArm64Main-9999.0.0-SNAPSHOT.klib",
          "url": "ui-uikit-uikitarm64-9999.0.0-SNAPSHOT.klib",
          "size": 38956,
          "sha512": "d4672ffaa77ebcc1110c7b84dfb36f0ba38bc45127a08e97c2fbcc92f428c2223cacb337b170a5ab361562df77704770a21b9c04fce75805619f348f19150bab",
          "sha256": "de39d5d2a9f72387352ee587f85f551a7aafb723f6740ed43e045bf3de80c175",
          "sha1": "80cab971e5b2492f0f6812652803f193b2eadfdf",
          "md5": "5d0f696af3731d54ab2b30b1eacc618f"
        },
        {
          "name": "ui-uikit-uikitArm64Cinterop-utilsMain-9999.0.0-SNAPSHOT.klib",
          "url": "ui-uikit-uikitarm64-9999.0.0-SNAPSHOT-cinterop-utils.klib",
          "size": 16818,
          "sha512": "014e60b66a9ba4011147f3fceedbf861982b81f8e42fb817de5dfdf810bb871b1e7f878eb3f84ca406ccf47adc2988eaa6b204dc6d48459d03c39fbad9629d6b",
          "sha256": "76e9ddbe16ac13f9e353ec14681757b5735ff27bce8fce1d5225d45edd807884",
          "sha1": "d4d8d7821b124d153f03cdd6bbc1c42d1b622eda",
          "md5": "f7eadc7af5458dd76d74f43142fab44b"
        }
      ]
    },
    {
      "name": "uikitArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-uikit-uikitarm64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "ui-uikit-uikitarm64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 1490,
          "sha512": "d6dc3e7f01c622f0ea48c15b68dd3bd723a920b41f0b1cc815a262f8c90d27005f8dce99adc3b3ccf4812250ef7e74cf35479950fdf71a195a45d93ba5acbdb3",
          "sha256": "b786874f6ed58f0ba4b5a0c2e47b7361c73b1aaab5f7eb1d608a026944a86265",
          "sha1": "aba8ee840667a30a5ec3805304797479188efcc4",
          "md5": "740df642ae42cb3d618bbb1f1d5693f3"
        }
      ]
    },
    {
      "name": "uikitArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-uikit-uikitarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "url": "ui-uikit-uikitarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "size": 29988,
          "sha512": "7ad623c23f74cfa483d5ae380f53e7554d79662ab8301507f7744b25ce5fc50652de8ddb268939ae51a88a372ee205853d8de68d5668c5fb4a66394169ac4e1e",
          "sha256": "8a25ea7afc32fa284d4548a453a15529e18e691c42045a9ad34c9703327dece0",
          "sha1": "19ecd3e3765744ae5f5af9dfe620e053c4062d7c",
          "md5": "27636dcf9f4f731652f87dfa62f0dfd6"
        }
      ]
    }
  ]
}