{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lifecycle-viewmodel/9999.0.0-SNAPSHOT/lifecycle-viewmodel-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.androidx.lifecycle",
    "module": "lifecycle-viewmodel",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-js-9999.0.0-SNAPSHOT.klib",
          "url": "lifecycle-viewmodel-js-9999.0.0-SNAPSHOT.klib",
          "size": 48016,
          "sha512": "467506ca7d3d98c92479f87f4b733a61d34f877b16fc6b27b586d6b941a8ba75442e31378525687166db6f4a7ff206b720c369d1bebb5a7956ba79abaaec3c31",
          "sha256": "99780b24a1b1cf8b1e60171c61b69294d5e7b4317fe4f46ea4a20c36beebac9c",
          "sha1": "6d20c918a3681e5ef4b05ef19c1fd7e24b14ba24",
          "md5": "71255f18bf6827f1e7fc6b236e3233aa"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-js-9999.0.0-SNAPSHOT.klib",
          "url": "lifecycle-viewmodel-js-9999.0.0-SNAPSHOT.klib",
          "size": 48016,
          "sha512": "467506ca7d3d98c92479f87f4b733a61d34f877b16fc6b27b586d6b941a8ba75442e31378525687166db6f4a7ff206b720c369d1bebb5a7956ba79abaaec3c31",
          "sha256": "99780b24a1b1cf8b1e60171c61b69294d5e7b4317fe4f46ea4a20c36beebac9c",
          "sha1": "6d20c918a3681e5ef4b05ef19c1fd7e24b14ba24",
          "md5": "71255f18bf6827f1e7fc6b236e3233aa"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-js-9999.0.0-SNAPSHOT-sources.jar",
          "url": "lifecycle-viewmodel-js-9999.0.0-SNAPSHOT-sources.jar",
          "size": 30193,
          "sha512": "939cc360a5656ac54fb0c16cd0e1cda9e41d512edcaae44cf3e85583ab5fdbd6cc206a2f329b46fca978aa2389aa5a695e733e2e931cd2ec68f1fdad57c0aba5",
          "sha256": "f927916ef82e3abd2e951fab64af16c6392ff42e214677c994b20d8351ce76b5",
          "sha1": "4da7570fb48d77932ae9228bf13917d7ce3dfcce",
          "md5": "99139f89b20613abdf90cbc7490033c9"
        }
      ]
    }
  ]
}