{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material3-window-size-class/9999.0.0-SNAPSHOT/material3-window-size-class-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.material3",
    "module": "material3-window-size-class",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "uikitSimArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-uikitSimArm64Main-9999.0.0-SNAPSHOT.klib",
          "url": "material3-window-size-class-uikitsimarm64-9999.0.0-SNAPSHOT.klib",
          "size": 20615,
          "sha512": "7baa9bec330b06942c5f1add750069cd58577734048029d4d3b2bbb24521f4c7b67f859cf9229163114dce426f7e62f9bdf44c6ddb8943e2b824a345fdac5124",
          "sha256": "16fd8e166edbc22bb9e9bf64b11fd50bd4d1f5fe54808a019344cad59fcdd287",
          "sha1": "dc88daa5b2728f7f6265e7546332d9da525d7b13",
          "md5": "087e5566ae122cc950b400a2a8f64243"
        }
      ]
    },
    {
      "name": "uikitSimArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "material3-window-size-class-uikitsimarm64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "material3-window-size-class-uikitsimarm64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 8215,
          "sha512": "1d1473b5d9871520074fa3026386c5b8dd4a35bc8038428a6f4c8b8aa6d10f8e4cb67f667f379e61b2f117cc886d4ce7a4199a7b82106abfcf96aa535cab03d9",
          "sha256": "cc82c5cf4d6a5db143e15fac3bc76b70b83967038c75c600ea8a560db3d49e2d",
          "sha1": "58c795afa7792c2495ec8d0fdc94d763bc549fcb",
          "md5": "db048b8ab965fdd3c285ab344872cf02"
        }
      ]
    },
    {
      "name": "uikitSimArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-uikitsimarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "url": "material3-window-size-class-uikitsimarm64-9999.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}