{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-tooling/9999.0.0-SNAPSHOT/ui-tooling-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-tooling",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-desktop-9999.0.0-SNAPSHOT.jar",
          "url": "ui-tooling-desktop-9999.0.0-SNAPSHOT.jar",
          "size": 28772,
          "sha512": "ed46d545e5b544d26bac0e9d36cffc97f07e9fdcc1186a8c9a172d0a15db895ea865db449d13ea1aac5a6cf51bd05366666bc597cb9ebe9aa72441f1fcb0f988",
          "sha256": "73b4bd75a60291e8519baecd1d21b4a623bde126b692b6ec2484a90e7214bc8d",
          "sha1": "35cc10704da31cc950031466aed73e7fddce471f",
          "md5": "002f075acfd629362c5a1679f8a77126"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-desktop-9999.0.0-SNAPSHOT.jar",
          "url": "ui-tooling-desktop-9999.0.0-SNAPSHOT.jar",
          "size": 28772,
          "sha512": "ed46d545e5b544d26bac0e9d36cffc97f07e9fdcc1186a8c9a172d0a15db895ea865db449d13ea1aac5a6cf51bd05366666bc597cb9ebe9aa72441f1fcb0f988",
          "sha256": "73b4bd75a60291e8519baecd1d21b4a623bde126b692b6ec2484a90e7214bc8d",
          "sha1": "35cc10704da31cc950031466aed73e7fddce471f",
          "md5": "002f075acfd629362c5a1679f8a77126"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ui-tooling-desktop-9999.0.0-SNAPSHOT-sources.jar",
          "url": "ui-tooling-desktop-9999.0.0-SNAPSHOT-sources.jar",
          "size": 9686,
          "sha512": "65fe282f5513da03801874bed00c21d175e977709bfcada7c8f0c7a1e298d2204c9ebd78f71bcfb85b8e851fbd7a494ceb533e13920ad6df11be29f697aebfc0",
          "sha256": "e5b70c83b7d80396eb4a3b429ef3dece9d27e1793dbb72f2bdef0dfe1e86f557",
          "sha1": "94f77e248ddce806cf83372c470a19b0d5aa6d23",
          "md5": "a972f2c495197b6e01a573644f9aceef"
        }
      ]
    }
  ]
}