{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.androidx.lifecycle",
    "module": "lifecycle-viewmodel-compose",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-9999.0.0-SNAPSHOT.jar",
          "url": "lifecycle-viewmodel-compose-9999.0.0-SNAPSHOT.jar",
          "size": 12104,
          "sha512": "25394050956de8d7086bc7c2b4ad425162310d52fb8c7014688f1fbcff55404ac8494dfa4d6459b1b0c86e82891f76d637a83db3d9b0a790bc3e9ad4937fe154",
          "sha256": "9245b7b0b6e145742ca191a2e6c49d47eee06839e6b2c9f9dbdcedf95bd54da9",
          "sha1": "0a0a51d2b2fffffe0be952dd3636ded6c5bebdba",
          "md5": "09b44586cb179a3809bc22e8c5e56b71"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-compose-9999.0.0-SNAPSHOT-sources.jar",
          "url": "lifecycle-viewmodel-compose-9999.0.0-SNAPSHOT-sources.jar",
          "size": 12342,
          "sha512": "4e61e7fa518335be3a1b7970debe9a21cd2aced5b48762877e0f042ca0e68c6515f735096a22e2725226ef62bcd0539e1ce06ade9933b8a2b17b15d37e861761",
          "sha256": "9bfa5ac6657a641d8067e61c29b1efc635c95ec7af0c2963d2e5bc79cecb13bc",
          "sha1": "0c2db6fed970b68f55296d6ffee2b76951faf4e6",
          "md5": "958230c3d13f3f70edb4ccba2bab68de"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-alpha12"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-alpha12"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ]
    },
    {
      "name": "debugSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-alpha12"
          }
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-alpha12"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-alpha12"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-alpha12"
          }
        }
      ]
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-compose-desktop/9999.0.0-SNAPSHOT/lifecycle-viewmodel-compose-desktop-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-viewmodel-compose-desktop",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-compose-desktop/9999.0.0-SNAPSHOT/lifecycle-viewmodel-compose-desktop-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-viewmodel-compose-desktop",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-compose-desktop/9999.0.0-SNAPSHOT/lifecycle-viewmodel-compose-desktop-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-viewmodel-compose-desktop",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-compose-js/9999.0.0-SNAPSHOT/lifecycle-viewmodel-compose-js-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-viewmodel-compose-js",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-compose-js/9999.0.0-SNAPSHOT/lifecycle-viewmodel-compose-js-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-viewmodel-compose-js",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-compose-js/9999.0.0-SNAPSHOT/lifecycle-viewmodel-compose-js-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-viewmodel-compose-js",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-compose-macosarm64/9999.0.0-SNAPSHOT/lifecycle-viewmodel-compose-macosarm64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-viewmodel-compose-macosarm64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-compose-macosarm64/9999.0.0-SNAPSHOT/lifecycle-viewmodel-compose-macosarm64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-viewmodel-compose-macosarm64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-compose-macosarm64/9999.0.0-SNAPSHOT/lifecycle-viewmodel-compose-macosarm64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-viewmodel-compose-macosarm64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-compose-macosx64/9999.0.0-SNAPSHOT/lifecycle-viewmodel-compose-macosx64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-viewmodel-compose-macosx64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-compose-macosx64/9999.0.0-SNAPSHOT/lifecycle-viewmodel-compose-macosx64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-viewmodel-compose-macosx64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-compose-macosx64/9999.0.0-SNAPSHOT/lifecycle-viewmodel-compose-macosx64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-viewmodel-compose-macosx64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "uikitArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-compose-uikitarm64/9999.0.0-SNAPSHOT/lifecycle-viewmodel-compose-uikitarm64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-viewmodel-compose-uikitarm64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "uikitArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-compose-uikitarm64/9999.0.0-SNAPSHOT/lifecycle-viewmodel-compose-uikitarm64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-viewmodel-compose-uikitarm64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "uikitArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-compose-uikitarm64/9999.0.0-SNAPSHOT/lifecycle-viewmodel-compose-uikitarm64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-viewmodel-compose-uikitarm64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "uikitSimArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-compose-uikitsimarm64/9999.0.0-SNAPSHOT/lifecycle-viewmodel-compose-uikitsimarm64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-viewmodel-compose-uikitsimarm64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "uikitSimArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-compose-uikitsimarm64/9999.0.0-SNAPSHOT/lifecycle-viewmodel-compose-uikitsimarm64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-viewmodel-compose-uikitsimarm64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "uikitSimArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-compose-uikitsimarm64/9999.0.0-SNAPSHOT/lifecycle-viewmodel-compose-uikitsimarm64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-viewmodel-compose-uikitsimarm64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "uikitX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-compose-uikitx64/9999.0.0-SNAPSHOT/lifecycle-viewmodel-compose-uikitx64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-viewmodel-compose-uikitx64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "uikitX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-compose-uikitx64/9999.0.0-SNAPSHOT/lifecycle-viewmodel-compose-uikitx64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-viewmodel-compose-uikitx64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "uikitX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-compose-uikitx64/9999.0.0-SNAPSHOT/lifecycle-viewmodel-compose-uikitx64-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-viewmodel-compose-uikitx64",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-compose-wasm-js/9999.0.0-SNAPSHOT/lifecycle-viewmodel-compose-wasm-js-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-viewmodel-compose-wasm-js",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-compose-wasm-js/9999.0.0-SNAPSHOT/lifecycle-viewmodel-compose-wasm-js-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-viewmodel-compose-wasm-js",
        "version": "9999.0.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-compose-wasm-js/9999.0.0-SNAPSHOT/lifecycle-viewmodel-compose-wasm-js-9999.0.0-SNAPSHOT.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-viewmodel-compose-wasm-js",
        "version": "9999.0.0-SNAPSHOT"
      }
    }
  ]
}