{
  "formatVersion": "1.1",
  "component": {
    "url": "../../animation-core/9999.0.0-SNAPSHOT/animation-core-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.animation",
    "module": "animation-core",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "animation-core-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 445412,
          "sha512": "6d98e2d3b6fcc3a3f0f8f3ffa21c4cf1aef204599c4cfcc1dcf0c3ce9ac1366f24c810e04ac5b6aa4517e367869e61cf9c0f6025756a9b79a93968d779076bcb",
          "sha256": "b17ac3b06697d4ba11b19c6ad0a82361dbade2748c950283171b63702f4d9450",
          "sha1": "02e238f82cb4f70839b5482f0151c982d911b318",
          "md5": "c4e69825183a321b2c6e364f8311c73b"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "animation-core-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 445412,
          "sha512": "6d98e2d3b6fcc3a3f0f8f3ffa21c4cf1aef204599c4cfcc1dcf0c3ce9ac1366f24c810e04ac5b6aa4517e367869e61cf9c0f6025756a9b79a93968d779076bcb",
          "sha256": "b17ac3b06697d4ba11b19c6ad0a82361dbade2748c950283171b63702f4d9450",
          "sha1": "02e238f82cb4f70839b5482f0151c982d911b318",
          "md5": "c4e69825183a321b2c6e364f8311c73b"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "animation-core-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "url": "animation-core-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "size": 111735,
          "sha512": "de342812a3f683a748f789630baf767220fe36bd50222c1e0708917c130205bacfc36759b7f101f2cc17688eb6b3524a860e15dd450dc874aa38db32f2e2802a",
          "sha256": "3e5139f01715c1f7a118884fbdddbfa9a3dc47ef2f5df6dfa81081ca988b8cd3",
          "sha1": "30de17e1f737583fdb3879b75f655ce0d36bc3b6",
          "md5": "f9de1fc56fece1d0973ebb2584a429a0"
        }
      ]
    }
  ]
}