{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lifecycle-viewmodel-savedstate/9999.0.0-SNAPSHOT/lifecycle-viewmodel-savedstate-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.androidx.lifecycle",
    "module": "lifecycle-viewmodel-savedstate",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "lifecycle-viewmodel-savedstate-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 43173,
          "sha512": "d3496418fc95bb580962b56923ec2cb3b677a27832f6d94123ee78f92ab6e5badf097108ae21f1ff11889bcbf75e4bc375532452323ef99784fe754ac4d52128",
          "sha256": "f343d686c3393cc32204af45e077e44e00b801d8f5ce8d033fdd7970b73161cb",
          "sha1": "7175b25427d25fa39479bcab22b234234c24079e",
          "md5": "7287e24d65898f0ea657bd11cafc0a44"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-wasm-js-9999.0.0-SNAPSHOT.klib",
          "url": "lifecycle-viewmodel-savedstate-wasm-js-9999.0.0-SNAPSHOT.klib",
          "size": 43173,
          "sha512": "d3496418fc95bb580962b56923ec2cb3b677a27832f6d94123ee78f92ab6e5badf097108ae21f1ff11889bcbf75e4bc375532452323ef99784fe754ac4d52128",
          "sha256": "f343d686c3393cc32204af45e077e44e00b801d8f5ce8d033fdd7970b73161cb",
          "sha1": "7175b25427d25fa39479bcab22b234234c24079e",
          "md5": "7287e24d65898f0ea657bd11cafc0a44"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "url": "lifecycle-viewmodel-savedstate-wasm-js-9999.0.0-SNAPSHOT-sources.jar",
          "size": 19783,
          "sha512": "a48fde5e13635d3b20b8035776adda646036125565b07c0d5ca8998ac6ad174d14a27c3bb4e89d803cb91060bee708f89354ab4c6ec1fd3de59a2b1f6d50ad43",
          "sha256": "a1d8561a2ec4a07e41d350b1e65787116d18fdf279036bc5da7981cb7e6aaec5",
          "sha1": "49fe401d2b5bb92d7a040cf534100d220ace34e6",
          "md5": "51ed84674b252ff25cc4e153787b2333"
        }
      ]
    }
  ]
}