{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-graphics/9999.0.0-SNAPSHOT/ui-graphics-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-graphics",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.9.3"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-js-9999.0.0-SNAPSHOT.klib",
          "url": "ui-graphics-js-9999.0.0-SNAPSHOT.klib",
          "size": 660953,
          "sha512": "fb937b7efe6a9434849a3ca807eeaf8d8ab8ccd799ad4e9840cdb1eaf11b14d8ffe266d0e0c02094d2af05f28c5a6d1bcf90902d62677f7d07c47b2ffda24895",
          "sha256": "6915d58882e5291c42984783ab110f83a6fa3f6a7978049cfe4ef4d38edeb6b2",
          "sha1": "9d29b20ade4bed5254005f8675e564d1a69d79ef",
          "md5": "b08f9c97f5ec7a8617bd47b48b66be2e"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.9.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-js-9999.0.0-SNAPSHOT.klib",
          "url": "ui-graphics-js-9999.0.0-SNAPSHOT.klib",
          "size": 660953,
          "sha512": "fb937b7efe6a9434849a3ca807eeaf8d8ab8ccd799ad4e9840cdb1eaf11b14d8ffe266d0e0c02094d2af05f28c5a6d1bcf90902d62677f7d07c47b2ffda24895",
          "sha256": "6915d58882e5291c42984783ab110f83a6fa3f6a7978049cfe4ef4d38edeb6b2",
          "sha1": "9d29b20ade4bed5254005f8675e564d1a69d79ef",
          "md5": "b08f9c97f5ec7a8617bd47b48b66be2e"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "ui-graphics-js-9999.0.0-SNAPSHOT-sources.jar",
          "url": "ui-graphics-js-9999.0.0-SNAPSHOT-sources.jar",
          "size": 223974,
          "sha512": "486666d925a95341ba07167ac47270a3031bd7b67db2507436596ba1d423e190e4854cb4e473cb84a84cc99f072d1d3b53c4e1669304b275d5f32a346598f42f",
          "sha256": "c5d90d314ebc1b09edda0ecd664bb1e2b8499690c791cdc4a0a8a9053dd36520",
          "sha1": "c4002beda9f6bfb356509d6f83e22443a1eccf11",
          "md5": "7d2beb0fac9eb05b620e131e16126de8"
        }
      ]
    }
  ]
}