{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lifecycle-runtime/9999.0.0-SNAPSHOT/lifecycle-runtime-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.androidx.lifecycle",
    "module": "lifecycle-runtime",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-linuxArm64Main-9999.0.0-SNAPSHOT.klib",
          "url": "lifecycle-runtime-linuxarm64-9999.0.0-SNAPSHOT.klib",
          "size": 37495,
          "sha512": "6c17846197ffd3d6e0b6e0be1ff3e881bdf86d2c5e6f6830178fa0323ea9272356db5423b361b8da0a435b47ac3124b08de0e0ea38970ed797a2f49715c04445",
          "sha256": "15601235b8922e18bba47e4c1b58d43f929a7265c4efb81fed2e5d665c609088",
          "sha1": "12038ed1f0d3d720ef8683a712276cb1fcc27931",
          "md5": "7a0e3320cc6cf813269910ddceb15be6"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "lifecycle-runtime-linuxarm64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "lifecycle-runtime-linuxarm64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 16213,
          "sha512": "e4881661f2f10785ad8781db9e20ede87c31501c58217ef2e1d8ac1056bff783a8df4a2ccd584d238898d5486ff7fe966823a2c7b3a157828006d04e97dccf6f",
          "sha256": "3876298b506fcebea0d444dbcbfdeda19d9e1bfe65b030969df3fc4cff0361b2",
          "sha1": "1fcdd4bb960d91ee85debe491479b55846a3b037",
          "md5": "f0f108e4feeddd964e5597c0a93049c7"
        }
      ]
    }
  ]
}