{
  "formatVersion": "1.1",
  "component": {
    "url": "../../navigation-common/9999.0.0-SNAPSHOT/navigation-common-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.androidx.navigation",
    "module": "navigation-common",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-linuxArm64Main-9999.0.0-SNAPSHOT.klib",
          "url": "navigation-common-linuxarm64-9999.0.0-SNAPSHOT.klib",
          "size": 314511,
          "sha512": "e23bff233f2a4201777b29c10e1b69e48fe9a2ed72d9b869280b56556d2a9922385d7004ec356ad011ec3b715f58e10c4e07dd75634b2d692df905cc398e0be8",
          "sha256": "cdfc86fc6d75bba4c51671fc9a078e51919b608711211d896c1130c393bc3b60",
          "sha1": "8424a7f245853b42c0bd7afe4234b6e61f8b76d6",
          "md5": "32cc06997d04f94d0579a8cf3f2f4d8f"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "navigation-common-linuxarm64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "navigation-common-linuxarm64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 102057,
          "sha512": "b6d9b7233b614b65fb94e7ff444d95b5ee7b7fb32a0d30e1e27b3bdae22b3acdbf1e9e34003a93578d4637819e083fc4eb9b97cac4f4c8aed1a9504e565d5a14",
          "sha256": "973dcaed95c078183d72a4670e699c2d069c8958dfc5d3c112de796ce672970b",
          "sha1": "36bec945b854a7e4c61468f419ac5dd17db19a32",
          "md5": "dcdc5bfc226859fe45be02e0d855574d"
        }
      ]
    }
  ]
}