{
  "formatVersion": "1.1",
  "component": {
    "url": "../../animation/9999.0.0-SNAPSHOT/animation-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.compose.animation",
    "module": "animation",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "animation-macosX64Main-9999.0.0-SNAPSHOT.klib",
          "url": "animation-macosx64-9999.0.0-SNAPSHOT.klib",
          "size": 359006,
          "sha512": "70acfcc5a0b55c1a3f64dae4402f0a64ce8fcdb65fb77688c2ee03818b56970bb3046e44e0faf26488f1a951a99e1b83190118ddeb6a3bf3910d10e88b643f69",
          "sha256": "5aca54fb58489cf864d6a7efaa8f9a9a74916743127df3e05e581bf6e8cf139d",
          "sha1": "a787f65c496d2bbe05813eb31748e23507746ce5",
          "md5": "5bc95ebdacdd5062b2fd8197324948a4"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "animation-macosx64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "animation-macosx64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 77241,
          "sha512": "fc2220abe0c863fc0e17f1665c2533ba142fa619bd54a6c5175be84a27b4c09ea074f7a7ab13759e239f7032806c7e6b3596256ce2b3a2da2a0e756cb8c2fe60",
          "sha256": "777189dd91599eb558799a835486806533e12bbeb38f301f8d10f65d62d96fe4",
          "sha1": "0701d11476b2f45a8013ac964e45aed911ef63e7",
          "md5": "34f86b9a7aab627263c0ff3c370b8471"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "animation-macosx64-9999.0.0-SNAPSHOT-metadata.jar",
          "url": "animation-macosx64-9999.0.0-SNAPSHOT-metadata.jar",
          "size": 3983,
          "sha512": "3e0f4c67c7fae45176afc46ef70b9b3c5aa4ce78b2ffe34cbf6482e636aaee2fb08aa8fa12012f2285412c19d3545dff928a8f26e8c571e123c53e02b6ae2d9d",
          "sha256": "ac99532051a982c7e19d97b7a5d4dc368186a2a4cc9bc7cf3426c367802b8372",
          "sha1": "95e2f3ef47b9c6664ebad9f81735a63fe5816074",
          "md5": "11992664afd8b09149fac0b04aa0c92c"
        }
      ]
    }
  ]
}