{
  "formatVersion": "1.1",
  "component": {
    "url": "../../navigation-common/9999.0.0-SNAPSHOT/navigation-common-9999.0.0-SNAPSHOT.module",
    "group": "org.jetbrains.androidx.navigation",
    "module": "navigation-common",
    "version": "9999.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "9999.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-linuxX64Main-9999.0.0-SNAPSHOT.klib",
          "url": "navigation-common-linuxx64-9999.0.0-SNAPSHOT.klib",
          "size": 314481,
          "sha512": "742fe76e4ff81d779089e13525e000d62e13a881eb6eaaedf8851aad65e952bc10baf16e16881fdca7bbcdbf00cb5c8f9d5be6b068dbb3cee6e68c844b941ff6",
          "sha256": "49a9b758c06800ea9a210d71e4afe1429e271865ae70dc716047eaaad57ee19f",
          "sha1": "d5a6f101b726fca9f3a580cae448db7590cc3c70",
          "md5": "f0b80433be180df378ec68c2dba950d4"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "navigation-common-linuxx64-9999.0.0-SNAPSHOT-sources.jar",
          "url": "navigation-common-linuxx64-9999.0.0-SNAPSHOT-sources.jar",
          "size": 102057,
          "sha512": "b6d9b7233b614b65fb94e7ff444d95b5ee7b7fb32a0d30e1e27b3bdae22b3acdbf1e9e34003a93578d4637819e083fc4eb9b97cac4f4c8aed1a9504e565d5a14",
          "sha256": "973dcaed95c078183d72a4670e699c2d069c8958dfc5d3c112de796ce672970b",
          "sha1": "36bec945b854a7e4c61468f419ac5dd17db19a32",
          "md5": "dcdc5bfc226859fe45be02e0d855574d"
        }
      ]
    }
  ]
}