name: CfW tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "jb-main"

jobs:
  cfw-tests:
    runs-on: ubuntu-24.04
    name: CfW tests
    steps:
      - name: Print dependencies versions
        run: |
          google-chrome-stable --version
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: install Android SDK
        run: ./jbdeps/android-sdk/downloadAndroidSdk
      - name: Run CfW tests
        run: xvfb-run -a ./gradlew :mpp:testWeb --no-parallel
